// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using FluentValidation;
using MB.Data.DTO;

namespace MB.Data.Validator
{
    public class UserPermissionValidator : AbstractValidator<UserPermissionDTO>
    {
        public UserPermissionValidator()
        {
            RuleFor(UserPermission => UserPermission.Name).NotEmpty().WithMessage("请填写权限名称");

            RuleFor(UserPermission => UserPermission.Controller).NotEmpty().WithMessage("请填写权限控制器");

            RuleFor(UserPermission => UserPermission.Action).NotEmpty().WithMessage("请填写权限Action");

            RuleFor(UserPermission => UserPermission.Group).NotEmpty().WithMessage("请填选择权限分组");
        }
    }
}

