// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using FluentValidation;
using MB.Data.DTO;

namespace MB.Data.Validator
{
    public class UserActivitiesValidator : AbstractValidator<UserActivitiesDTO>
    {
        public UserActivitiesValidator()
        {
            //RuleFor(UserActivities => UserActivities.Name).NotNull().WithMessage("{PropertyName} is required");
        }
    }
}

