// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

namespace MB.Controllers
{
    [RoutePrefix("api/Order")]
    public class OrderController : ApiController
    {
        private IOrderService OrderService;
        public OrderController(
            IOrderService _OrderService
          )
        {
            this.OrderService = _OrderService;
        }

        [Route("")]
        public ApiListResult<OrderDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = OrderService.GetAll().Where(x => !x.Deleted).ProjectTo<OrderDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<OrderDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<OrderDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(OrderDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            OrderDTO Order = await OrderService.GetAll().Where(x => x.Id == id && !x.Deleted).ProjectTo<OrderDTO>().FirstOrDefaultAsync();
            if (Order == null)
            {
                return NotFound();
            }
            return Ok(Order);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(OrderDTO))]
        public async Task<IHttpActionResult> Create([FromBody]OrderDTO OrderDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = OrderDto.ToEntity();

            entity.CreateUserId = User.Identity.GetUserId();
            entity.CreateTime = DateTime.Now;
            await OrderService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(OrderDTO))]
        public async Task<IHttpActionResult> Update([FromBody]OrderDTO OrderDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await OrderService.FindOneAsync(OrderDto.Id);
            entity = OrderDto.ToEntity(entity);
            entity.LastUserId = User.Identity.GetUserId();
            entity.LastTime = DateTime.Now;
            await OrderService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(OrderDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            Order entity = await OrderService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await OrderService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




