// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
	public class DepartmentProfile : BaseProfile
    {
        public DepartmentProfile() : base("DepartmentProfile")
        {
        }

		protected override void CreateMaps()
        {
			 
			CreateMap<Department, DepartmentDTO>()
;

			 
			CreateMap<DepartmentDTO, Department>()
					.ForMember(entity => entity.CreateUserId, o => o.Ignore())
					.ForMember(entity => entity.CreateTime, o => o.Ignore())
					.ForMember(entity => entity.LastUserId, o => o.Ignore())
					.ForMember(entity => entity.LastTime, o => o.Ignore())
					.ForMember(entity => entity.Deleted, o => o.Ignore())
					.ForMember(entity => entity.ParentDepartment, o => o.Ignore())
					.ForMember(entity => entity.ChildDepartments, o => o.Ignore())
					.ForMember(entity => entity.Jobs, o => o.Ignore())
;
        }
    }
}
