// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
    public static class MappingExtensions
    {

        public static DepartmentDTO ToModel(this Department entity)
        {
            return Mapper.Map<Department, DepartmentDTO>(entity);
        }

        public static Department ToEntity(this DepartmentDTO dto)
        {
            return Mapper.Map<DepartmentDTO, Department>(dto);
        }

        public static Department ToEntity(this DepartmentDTO dto, Department entity)
        {
            return Mapper.Map(dto, entity);
        }

        public static JobDTO ToModel(this Job entity)
        {
            return Mapper.Map<Job, JobDTO>(entity);
        }

        public static Job ToEntity(this JobDTO dto)
        {
            return Mapper.Map<JobDTO, Job>(dto);
        }

        public static Job ToEntity(this JobDTO dto, Job entity)
        {
            return Mapper.Map(dto, entity);
        }

        public static UserActivitiesDTO ToModel(this UserActivities entity)
        {
            return Mapper.Map<UserActivities, UserActivitiesDTO>(entity);
        }

        public static UserActivities ToEntity(this UserActivitiesDTO dto)
        {
            return Mapper.Map<UserActivitiesDTO, UserActivities>(dto);
        }

        public static UserActivities ToEntity(this UserActivitiesDTO dto, UserActivities entity)
        {
            return Mapper.Map(dto, entity);
        }

        public static UserPermissionDTO ToModel(this UserPermission entity)
        {
            return Mapper.Map<UserPermission, UserPermissionDTO>(entity);
        }

        public static UserPermission ToEntity(this UserPermissionDTO dto)
        {
            return Mapper.Map<UserPermissionDTO, UserPermission>(dto);
        }

        public static UserPermission ToEntity(this UserPermissionDTO dto, UserPermission entity)
        {
            return Mapper.Map(dto, entity);
        }

        public static UserRoleDTO ToModel(this UserRole entity)
        {
            return Mapper.Map<UserRole, UserRoleDTO>(entity);
        }

        public static UserRole ToEntity(this UserRoleDTO dto)
        {
            return Mapper.Map<UserRoleDTO, UserRole>(dto);
        }

        public static UserRole ToEntity(this UserRoleDTO dto, UserRole entity)
        {
            return Mapper.Map(dto, entity);
        }


    }
}
