// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
    public class ProductProfile : BaseProfile
    {
        public ProductProfile() : base("ProductProfile")
        {
        }

        protected override void CreateMaps()
        {

            CreateMap<Product, ProductDTO>();


            CreateMap<ProductDTO, Product>()
                    .ForMember(entity => entity.Distance, o => o.Ignore())
                    .ForMember(entity => entity.CreateUserId, o => o.Ignore())
                    .ForMember(entity => entity.CreateTime, o => o.Ignore())
                    .ForMember(entity => entity.LastUserId, o => o.Ignore())
                    .ForMember(entity => entity.LastTime, o => o.Ignore())
                    .ForMember(entity => entity.Deleted, o => o.Ignore())
                    .ForMember(entity => entity.Category, o => o.Ignore())
                    .ForMember(entity => entity.Manufacturer, o => o.Ignore())
                    .ForMember(entity => entity.ProductCarCate, o => o.Ignore())
                    .ForMember(entity => entity.ProductStorageQuantity, o => o.Ignore())
                    .ForMember(entity => entity.ProductSpecificationAttributes, o => o.Ignore())
                    .ForMember(entity => entity.ProductAttributeMappings, o => o.Ignore())
;
        }
    }
}
