// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
	public class ProductAttributeCategoryMappingProfile : BaseProfile
    {
        public ProductAttributeCategoryMappingProfile() : base("ProductAttributeCategoryMappingProfile")
        {
        }

		protected override void CreateMaps()
        {
			 
			CreateMap<ProductAttributeCategoryMapping, ProductAttributeCategoryMappingDTO>()
;

			 
			CreateMap<ProductAttributeCategoryMappingDTO, ProductAttributeCategoryMapping>()
					.ForMember(entity => entity.ProductAttribute, o => o.Ignore())
					.ForMember(entity => entity.Category, o => o.Ignore())
;
        }
    }
}
