// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
	public class SpecificationAttributeProfile : BaseProfile
    {
        public SpecificationAttributeProfile() : base("SpecificationAttributeProfile")
        {
        }

		protected override void CreateMaps()
        {
			 
			CreateMap<SpecificationAttribute, SpecificationAttributeDTO>()
;

			 
			CreateMap<SpecificationAttributeDTO, SpecificationAttribute>()
					.ForMember(entity => entity.SpecificationAttributeOptions, o => o.Ignore())
;
        }
    }
}
