// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;

namespace MB.Data.AutoMapper
{
	public class SpecificationAttributeCategoryMappingProfile : BaseProfile
    {
        public SpecificationAttributeCategoryMappingProfile() : base("SpecificationAttributeCategoryMappingProfile")
        {
        }

		protected override void CreateMaps()
        {
			 
			CreateMap<SpecificationAttributeCategoryMapping, SpecificationAttributeCategoryMappingDTO>()
;

			 
			CreateMap<SpecificationAttributeCategoryMappingDTO, SpecificationAttributeCategoryMapping>()
					.ForMember(entity => entity.SpecificationAttribute, o => o.Ignore())
					.ForMember(entity => entity.Category, o => o.Ignore())
;
        }
    }
}
