// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AutoMapper;
using SQ.Core.AutoMapper;
using MB.Data.Models;
using MB.Data.DTO;
using System.Data.Entity.Spatial;

namespace MB.Data.AutoMapper
{
    public class StorageProfile : BaseProfile
    {
        public StorageProfile() : base("StorageProfile")
        {
        }

        protected override void CreateMaps()
        {

            CreateMap<Storage, StorageDTO>()
                 .ForMember(dto => dto.Latitude, o => o.MapFrom(ety=>ety.Location.Latitude))
                 .ForMember(dto => dto.Longitude, o => o.MapFrom(ety => ety.Location.Longitude))
                 .ForMember(dto => dto.Distance, o => o.Ignore());


            CreateMap<StorageDTO, Storage>()
                 .ForMember(entity => entity.Location, o => o.MapFrom(dto => DbGeography.FromText(string.Format("POINT({0} {1})", dto.Longitude, dto.Latitude))))
                 .ForMember(entity => entity.CreateUserId, o => o.Ignore())
                 .ForMember(entity => entity.CreateTime, o => o.Ignore())
                 .ForMember(entity => entity.LastUserId, o => o.Ignore())
                 .ForMember(entity => entity.LastTime, o => o.Ignore())
                 .ForMember(entity => entity.Deleted, o => o.Ignore());
        }
    }
}
