// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as addressTypes from '../contants/address';

export function getAll(params) {
  return {
    types: [addressTypes.GET_ALL_ADDRESS, addressTypes.GET_ALL_ADDRESS_SUCCESS, addressTypes.GET_ALL_ADDRESS_FAIL],
    promise: (client) => client.get('/address',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [addressTypes.GET_ONE_ADDRESS, addressTypes.GET_ONE_ADDRESS_SUCCESS, addressTypes.GET_ONE_ADDRESS_FAIL],
    promise: (client) => client.get('/address/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [addressTypes.CREATE_ADDRESS, addressTypes.CREATE_ADDRESS_SUCCESS, addressTypes.CREATE_ADDRESS_FAIL],
    promise: (client) => client.post('/address', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [addressTypes.UPDATE_ADDRESS, addressTypes.UPDATE_ADDRESS_SUCCESS, addressTypes.UPDATE_ADDRESS_FAIL],
    promise: (client) => client.put('/address', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [addressTypes.DELETE_ADDRESS, addressTypes.DELETE_ADDRESS_SUCCESS, addressTypes.DELETE_ADDRESS_FAIL],
    promise: (client) => client.del('/address/'+id, {
		token: true
    })
  };
}


