// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as orderItemTypes from '../contants/orderItem';

export function getAll(params) {
  return {
    types: [orderItemTypes.GET_ALL_ORDERITEM, orderItemTypes.GET_ALL_ORDERITEM_SUCCESS, orderItemTypes.GET_ALL_ORDERITEM_FAIL],
    promise: (client) => client.get('/orderItem',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [orderItemTypes.GET_ONE_ORDERITEM, orderItemTypes.GET_ONE_ORDERITEM_SUCCESS, orderItemTypes.GET_ONE_ORDERITEM_FAIL],
    promise: (client) => client.get('/orderItem/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [orderItemTypes.CREATE_ORDERITEM, orderItemTypes.CREATE_ORDERITEM_SUCCESS, orderItemTypes.CREATE_ORDERITEM_FAIL],
    promise: (client) => client.post('/orderItem', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [orderItemTypes.UPDATE_ORDERITEM, orderItemTypes.UPDATE_ORDERITEM_SUCCESS, orderItemTypes.UPDATE_ORDERITEM_FAIL],
    promise: (client) => client.put('/orderItem', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [orderItemTypes.DELETE_ORDERITEM, orderItemTypes.DELETE_ORDERITEM_SUCCESS, orderItemTypes.DELETE_ORDERITEM_FAIL],
    promise: (client) => client.del('/orderItem/'+id, {
		token: true
    })
  };
}


