// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productAttributeCategoryMappingTypes from '../contants/productAttributeCategoryMapping';

export function getAll(params) {
  return {
    types: [productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING, productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS, productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL],
    promise: (client) => client.get('/productAttributeCategoryMapping',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING, productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS, productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL],
    promise: (client) => client.get('/productAttributeCategoryMapping/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING, productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS, productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL],
    promise: (client) => client.post('/productAttributeCategoryMapping', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING, productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS, productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL],
    promise: (client) => client.put('/productAttributeCategoryMapping', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING, productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS, productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL],
    promise: (client) => client.del('/productAttributeCategoryMapping/'+id, {
		token: true
    })
  };
}


