// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as shoppingCartItemTypes from '../contants/shoppingCartItem';

export function getAll(params) {
  return {
    types: [shoppingCartItemTypes.GET_ALL_SHOPPINGCARTITEM, shoppingCartItemTypes.GET_ALL_SHOPPINGCARTITEM_SUCCESS, shoppingCartItemTypes.GET_ALL_SHOPPINGCARTITEM_FAIL],
    promise: (client) => client.get('/shoppingCartItem',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [shoppingCartItemTypes.GET_ONE_SHOPPINGCARTITEM, shoppingCartItemTypes.GET_ONE_SHOPPINGCARTITEM_SUCCESS, shoppingCartItemTypes.GET_ONE_SHOPPINGCARTITEM_FAIL],
    promise: (client) => client.get('/shoppingCartItem/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [shoppingCartItemTypes.CREATE_SHOPPINGCARTITEM, shoppingCartItemTypes.CREATE_SHOPPINGCARTITEM_SUCCESS, shoppingCartItemTypes.CREATE_SHOPPINGCARTITEM_FAIL],
    promise: (client) => client.post('/shoppingCartItem', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [shoppingCartItemTypes.UPDATE_SHOPPINGCARTITEM, shoppingCartItemTypes.UPDATE_SHOPPINGCARTITEM_SUCCESS, shoppingCartItemTypes.UPDATE_SHOPPINGCARTITEM_FAIL],
    promise: (client) => client.put('/shoppingCartItem', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [shoppingCartItemTypes.DELETE_SHOPPINGCARTITEM, shoppingCartItemTypes.DELETE_SHOPPINGCARTITEM_SUCCESS, shoppingCartItemTypes.DELETE_SHOPPINGCARTITEM_FAIL],
    promise: (client) => client.del('/shoppingCartItem/'+id, {
		token: true
    })
  };
}


