// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
    public class CarMappingService : ICarMappingService
    {
        #region Fields

        private readonly IRepository<CarMapping> _CarMappingRepository;

        #endregion

        #region Ctor

        public CarMappingService(IRepository<CarMapping> CarMappingRepository
           )
        {
            this._CarMappingRepository = CarMappingRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(CarMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CarMapping");

            return await _CarMappingRepository.DeleteAsync(entity);
        }

        public async Task<CarMapping> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _CarMappingRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<CarMapping> GetAll()
        {
            return _CarMappingRepository.Table;
        }

        public IPagedList<CarMapping> GetPageList(int pageIndex, int pageSize)
        {
            var query = _CarMappingRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<CarMapping>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(CarMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CarMapping");
            return await _CarMappingRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(CarMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CarMapping");

            return await _CarMappingRepository.UpdateAsync(entity);
        }
    }
}
