// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class CategoryService : ICategoryService
    {
		   #region Fields

        private readonly IRepository<Category> _CategoryRepository;

        #endregion

        #region Ctor

        public CategoryService(IRepository<Category> CategoryRepository
           )
        {
            this._CategoryRepository = CategoryRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Category entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Category");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Category> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _CategoryRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Category> GetAll()
        {
            return _CategoryRepository.Table;
        }

        public IPagedList<Category> GetPageList(int pageIndex, int pageSize)
        {
            var query = _CategoryRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Category>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Category entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Category");
            return await _CategoryRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Category entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Category");

            return await _CategoryRepository.UpdateAsync(entity);
        }
    }
}
