// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
    public class CityCateService : ICityCateService
    {
        #region Fields

        private readonly IRepository<CityCate> _CityCateRepository;

        #endregion

        #region Ctor

        public CityCateService(IRepository<CityCate> CityCateRepository
           )
        {
            this._CityCateRepository = CityCateRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(CityCate entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CityCate");

            entity.Deleted = true;
            return await UpdateAsync(entity);
        }

        public async Task<CityCate> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _CityCateRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<CityCate> GetAll()
        {
            return _CityCateRepository.Table;
        }

        public IPagedList<CityCate> GetPageList(int pageIndex, int pageSize)
        {
            var query = _CityCateRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<CityCate>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(CityCate entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CityCate");
            return await _CityCateRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(CityCate entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CityCate");

            return await _CityCateRepository.UpdateAsync(entity);
        }
    }
}
