// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class DepartmentService : IDepartmentService
    {
		   #region Fields

        private readonly IRepository<Department> _DepartmentRepository;

        #endregion

        #region Ctor

        public DepartmentService(IRepository<Department> DepartmentRepository
           )
        {
            this._DepartmentRepository = DepartmentRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Department entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Department");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Department> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _DepartmentRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Department> GetAll()
        {
            return _DepartmentRepository.Table;
        }

        public IPagedList<Department> GetPageList(int pageIndex, int pageSize)
        {
            var query = _DepartmentRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Department>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Department entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Department");
            return await _DepartmentRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Department entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Department");

            return await _DepartmentRepository.UpdateAsync(entity);
        }
    }
}
