// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class JobService : IJobService
    {
		   #region Fields

        private readonly IRepository<Job> _JobRepository;

        #endregion

        #region Ctor

        public JobService(IRepository<Job> JobRepository
           )
        {
            this._JobRepository = JobRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Job entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Job");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Job> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _JobRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Job> GetAll()
        {
            return _JobRepository.Table;
        }

        public IPagedList<Job> GetPageList(int pageIndex, int pageSize)
        {
            var query = _JobRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Job>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Job entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Job");
            return await _JobRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Job entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Job");

            return await _JobRepository.UpdateAsync(entity);
        }
    }
}
