// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class OrderService : IOrderService
    {
		   #region Fields

        private readonly IRepository<Order> _OrderRepository;

        #endregion

        #region Ctor

        public OrderService(IRepository<Order> OrderRepository
           )
        {
            this._OrderRepository = OrderRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Order entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Order");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Order> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _OrderRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Order> GetAll()
        {
            return _OrderRepository.Table;
        }

        public IPagedList<Order> GetPageList(int pageIndex, int pageSize)
        {
            var query = _OrderRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Order>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Order entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Order");
            return await _OrderRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Order entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Order");

            return await _OrderRepository.UpdateAsync(entity);
        }
    }
}
