// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
    public class ProductStorageQuantityService : IProductStorageQuantityService
    {
        #region Fields

        private readonly IRepository<ProductStorageQuantity> _ProductStorageQuantityRepository;

        #endregion

        #region Ctor

        public ProductStorageQuantityService(IRepository<ProductStorageQuantity> ProductStorageQuantityRepository
           )
        {
            this._ProductStorageQuantityRepository = ProductStorageQuantityRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(ProductStorageQuantity entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductStorageQuantity");

            return await _ProductStorageQuantityRepository.DeleteAsync(entity);
        }

        public async Task<ProductStorageQuantity> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ProductStorageQuantityRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<ProductStorageQuantity> GetAll()
        {
            return _ProductStorageQuantityRepository.Table;
        }

        public IPagedList<ProductStorageQuantity> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ProductStorageQuantityRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<ProductStorageQuantity>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(ProductStorageQuantity entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductStorageQuantity");
            return await _ProductStorageQuantityRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(ProductStorageQuantity entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductStorageQuantity");

            return await _ProductStorageQuantityRepository.UpdateAsync(entity);
        }
    }
}
