// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class ProductAttributeMappingService : IProductAttributeMappingService
    {
		   #region Fields

        private readonly IRepository<ProductAttributeMapping> _ProductAttributeMappingRepository;

        #endregion

        #region Ctor

        public ProductAttributeMappingService(IRepository<ProductAttributeMapping> ProductAttributeMappingRepository
           )
        {
            this._ProductAttributeMappingRepository = ProductAttributeMappingRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(ProductAttributeMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeMapping");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<ProductAttributeMapping> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ProductAttributeMappingRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<ProductAttributeMapping> GetAll()
        {
            return _ProductAttributeMappingRepository.Table;
        }

        public IPagedList<ProductAttributeMapping> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ProductAttributeMappingRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<ProductAttributeMapping>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(ProductAttributeMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeMapping");
            return await _ProductAttributeMappingRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(ProductAttributeMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeMapping");

            return await _ProductAttributeMappingRepository.UpdateAsync(entity);
        }
    }
}
