// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class ProductService : IProductService
    {
		   #region Fields

        private readonly IRepository<Product> _ProductRepository;

        #endregion

        #region Ctor

        public ProductService(IRepository<Product> ProductRepository
           )
        {
            this._ProductRepository = ProductRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(Product entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Product");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<Product> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ProductRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<Product> GetAll()
        {
            return _ProductRepository.Table;
        }

        public IPagedList<Product> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ProductRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<Product>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(Product entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Product");
            return await _ProductRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(Product entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Product");

            return await _ProductRepository.UpdateAsync(entity);
        }
    }
}
