// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class ProductSpecificationAttributeService : IProductSpecificationAttributeService
    {
		   #region Fields

        private readonly IRepository<ProductSpecificationAttribute> _ProductSpecificationAttributeRepository;

        #endregion

        #region Ctor

        public ProductSpecificationAttributeService(IRepository<ProductSpecificationAttribute> ProductSpecificationAttributeRepository
           )
        {
            this._ProductSpecificationAttributeRepository = ProductSpecificationAttributeRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(ProductSpecificationAttribute entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductSpecificationAttribute");

            return await _ProductSpecificationAttributeRepository.DeleteAsync(entity);
        }

        public async Task<ProductSpecificationAttribute> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ProductSpecificationAttributeRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<ProductSpecificationAttribute> GetAll()
        {
            return _ProductSpecificationAttributeRepository.Table;
        }

        public IPagedList<ProductSpecificationAttribute> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ProductSpecificationAttributeRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<ProductSpecificationAttribute>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(ProductSpecificationAttribute entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductSpecificationAttribute");
            return await _ProductSpecificationAttributeRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(ProductSpecificationAttribute entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductSpecificationAttribute");

            return await _ProductSpecificationAttributeRepository.UpdateAsync(entity);
        }
    }
}
