// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class ShoppingCartItemService : IShoppingCartItemService
    {
		   #region Fields

        private readonly IRepository<ShoppingCartItem> _ShoppingCartItemRepository;

        #endregion

        #region Ctor

        public ShoppingCartItemService(IRepository<ShoppingCartItem> ShoppingCartItemRepository
           )
        {
            this._ShoppingCartItemRepository = ShoppingCartItemRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(ShoppingCartItem entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ShoppingCartItem");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<ShoppingCartItem> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ShoppingCartItemRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<ShoppingCartItem> GetAll()
        {
            return _ShoppingCartItemRepository.Table;
        }

        public IPagedList<ShoppingCartItem> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ShoppingCartItemRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<ShoppingCartItem>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(ShoppingCartItem entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ShoppingCartItem");
            return await _ShoppingCartItemRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(ShoppingCartItem entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ShoppingCartItem");

            return await _ShoppingCartItemRepository.UpdateAsync(entity);
        }
    }
}
