// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class UserRoleService : IUserRoleService
    {
		   #region Fields

        private readonly IRepository<UserRole> _UserRoleRepository;

        #endregion

        #region Ctor

        public UserRoleService(IRepository<UserRole> UserRoleRepository
           )
        {
            this._UserRoleRepository = UserRoleRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(UserRole entity)
        {
            if (entity == null)
                throw new ArgumentNullException("UserRole");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<UserRole> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _UserRoleRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<UserRole> GetAll()
        {
            return _UserRoleRepository.Table;
        }

        public IPagedList<UserRole> GetPageList(int pageIndex, int pageSize)
        {
            var query = _UserRoleRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<UserRole>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(UserRole entity)
        {
            if (entity == null)
                throw new ArgumentNullException("UserRole");
            return await _UserRoleRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(UserRole entity)
        {
            if (entity == null)
                throw new ArgumentNullException("UserRole");

            return await _UserRoleRepository.UpdateAsync(entity);
        }
    }
}
