// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as departmentTypes from '../contants/department';

export function getAll() {
  return {
    types: [departmentTypes.GET_ALL_DEPARTMENT, departmentTypes.GET_ALL_DEPARTMENT_SUCCESS, departmentTypes.GET_ALL_DEPARTMENT_FAIL],
    promise: (client) => client.get('/department',{
      token: true
    })
  };
}

export function getById(id) {
  return {
    types: [departmentTypes.GET_ONE_DEPARTMENT, departmentTypes.GET_ONE_DEPARTMENT_SUCCESS, departmentTypes.GET_ONE_DEPARTMENT_FAIL],
    promise: (client) => client.get('/department'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [department.CREATE_DEPARTMENT, department.CREATE_DEPARTMENT_SUCCESS, department.CREATE_DEPARTMENT_FAIL],
    promise: (client) => client.post('/department', {
      data: data,
	  token: true
    })
  };
}

export function update(id, data) {
  return {
    types: [department.UPDATE_DEPARTMENT, department.UPDATE_DEPARTMENT_SUCCESS, department.UPDATE_DEPARTMENT_FAIL],
    promise: (client) => client.put('/department/'+id, {
      data: data,
	  token: true
    })
  };
}

export function remove(id) {
  return {
    types: [department.DELETE_DEPARTMENT, department.DELETE_DEPARTMENT_SUCCESS, department.DELETE_DEPARTMENT_FAIL],
    promise: (client) => client.delete('/department/'+id, {
		token: true
    })
  };
}

