// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as departmentTypes from '../contants/department';

export function getAll(params) {
  return {
    types: [departmentTypes.GET_ALL_DEPARTMENT, departmentTypes.GET_ALL_DEPARTMENT_SUCCESS, departmentTypes.GET_ALL_DEPARTMENT_FAIL],
    promise: (client) => client.get('/department', {
      token: true,
      params
    })
  };
}

export function getCascader(params) {
  return {
    types: [departmentTypes.GET_DEPARTMENT_CASCADER, departmentTypes.GET_DEPARTMENT_CASCADER_SUCCESS, departmentTypes.GET_DEPARTMENT_CASCADER_FAIL],
    promise: (client) => client.get('/department/cascader', {
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [departmentTypes.GET_ONE_DEPARTMENT, departmentTypes.GET_ONE_DEPARTMENT_SUCCESS, departmentTypes.GET_ONE_DEPARTMENT_FAIL],
    promise: (client) => client.get('/department/' + id, {
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [departmentTypes.CREATE_DEPARTMENT, departmentTypes.CREATE_DEPARTMENT_SUCCESS, departmentTypes.CREATE_DEPARTMENT_FAIL],
    promise: (client) => client.post('/department', {
      data: data,
      token: true
    })
  };
}

export function update(data) {
  return {
    types: [departmentTypes.UPDATE_DEPARTMENT, departmentTypes.UPDATE_DEPARTMENT_SUCCESS, departmentTypes.UPDATE_DEPARTMENT_FAIL],
    promise: (client) => client.put('/department', {
      data: data,
      token: true
    })
  };
}

export function remove(id) {
  return {
    types: [departmentTypes.DELETE_DEPARTMENT, departmentTypes.DELETE_DEPARTMENT_SUCCESS, departmentTypes.DELETE_DEPARTMENT_FAIL],
    promise: (client) => client.delete('/department/' + id, {
      token: true
    })
  };
}

