// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productAttributeTypes from '../contants/productAttribute';

export function getAll(params) {
  return {
    types: [productAttributeTypes.GET_ALL_PRODUCTATTRIBUTE, productAttributeTypes.GET_ALL_PRODUCTATTRIBUTE_SUCCESS, productAttributeTypes.GET_ALL_PRODUCTATTRIBUTE_FAIL],
    promise: (client) => client.get('/productAttribute',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productAttributeTypes.GET_ONE_PRODUCTATTRIBUTE, productAttributeTypes.GET_ONE_PRODUCTATTRIBUTE_SUCCESS, productAttributeTypes.GET_ONE_PRODUCTATTRIBUTE_FAIL],
    promise: (client) => client.get('/productAttribute/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productAttributeTypes.CREATE_PRODUCTATTRIBUTE, productAttributeTypes.CREATE_PRODUCTATTRIBUTE_SUCCESS, productAttributeTypes.CREATE_PRODUCTATTRIBUTE_FAIL],
    promise: (client) => client.post('/productAttribute', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productAttributeTypes.UPDATE_PRODUCTATTRIBUTE, productAttributeTypes.UPDATE_PRODUCTATTRIBUTE_SUCCESS, productAttributeTypes.UPDATE_PRODUCTATTRIBUTE_FAIL],
    promise: (client) => client.put('/productAttribute', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productAttributeTypes.DELETE_PRODUCTATTRIBUTE, productAttributeTypes.DELETE_PRODUCTATTRIBUTE_SUCCESS, productAttributeTypes.DELETE_PRODUCTATTRIBUTE_FAIL],
    promise: (client) => client.del('/productAttribute/'+id, {
		token: true
    })
  };
}


