// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productAttributeValueTypes from '../contants/productAttributeValue';

export function getAll(params) {
  return {
    types: [productAttributeValueTypes.GET_ALL_PRODUCTATTRIBUTEVALUE, productAttributeValueTypes.GET_ALL_PRODUCTATTRIBUTEVALUE_SUCCESS, productAttributeValueTypes.GET_ALL_PRODUCTATTRIBUTEVALUE_FAIL],
    promise: (client) => client.get('/productAttributeValue',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productAttributeValueTypes.GET_ONE_PRODUCTATTRIBUTEVALUE, productAttributeValueTypes.GET_ONE_PRODUCTATTRIBUTEVALUE_SUCCESS, productAttributeValueTypes.GET_ONE_PRODUCTATTRIBUTEVALUE_FAIL],
    promise: (client) => client.get('/productAttributeValue/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productAttributeValueTypes.CREATE_PRODUCTATTRIBUTEVALUE, productAttributeValueTypes.CREATE_PRODUCTATTRIBUTEVALUE_SUCCESS, productAttributeValueTypes.CREATE_PRODUCTATTRIBUTEVALUE_FAIL],
    promise: (client) => client.post('/productAttributeValue', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productAttributeValueTypes.UPDATE_PRODUCTATTRIBUTEVALUE, productAttributeValueTypes.UPDATE_PRODUCTATTRIBUTEVALUE_SUCCESS, productAttributeValueTypes.UPDATE_PRODUCTATTRIBUTEVALUE_FAIL],
    promise: (client) => client.put('/productAttributeValue', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productAttributeValueTypes.DELETE_PRODUCTATTRIBUTEVALUE, productAttributeValueTypes.DELETE_PRODUCTATTRIBUTEVALUE_SUCCESS, productAttributeValueTypes.DELETE_PRODUCTATTRIBUTEVALUE_FAIL],
    promise: (client) => client.del('/productAttributeValue/'+id, {
		token: true
    })
  };
}


