// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productManufacturerTypes from '../contants/productManufacturer';

export function getAll(params) {
  return {
    types: [productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER, productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER_SUCCESS, productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER_FAIL],
    promise: (client) => client.get('/productManufacturer',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER, productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER_SUCCESS, productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER_FAIL],
    promise: (client) => client.get('/productManufacturer/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productManufacturerTypes.CREATE_PRODUCTMANUFACTURER, productManufacturerTypes.CREATE_PRODUCTMANUFACTURER_SUCCESS, productManufacturerTypes.CREATE_PRODUCTMANUFACTURER_FAIL],
    promise: (client) => client.post('/productManufacturer', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER, productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER_SUCCESS, productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER_FAIL],
    promise: (client) => client.put('/productManufacturer', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productManufacturerTypes.DELETE_PRODUCTMANUFACTURER, productManufacturerTypes.DELETE_PRODUCTMANUFACTURER_SUCCESS, productManufacturerTypes.DELETE_PRODUCTMANUFACTURER_FAIL],
    promise: (client) => client.del('/productManufacturer/'+id, {
		token: true
    })
  };
}


