// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productCarCateTypes from '../contants/productCarCate';

export function getAll(params) {
  return {
    types: [productCarCateTypes.GET_ALL_PRODUCTCARCATE, productCarCateTypes.GET_ALL_PRODUCTCARCATE_SUCCESS, productCarCateTypes.GET_ALL_PRODUCTCARCATE_FAIL],
    promise: (client) => client.get('/productCarCate',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productCarCateTypes.GET_ONE_PRODUCTCARCATE, productCarCateTypes.GET_ONE_PRODUCTCARCATE_SUCCESS, productCarCateTypes.GET_ONE_PRODUCTCARCATE_FAIL],
    promise: (client) => client.get('/productCarCate/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productCarCateTypes.CREATE_PRODUCTCARCATE, productCarCateTypes.CREATE_PRODUCTCARCATE_SUCCESS, productCarCateTypes.CREATE_PRODUCTCARCATE_FAIL],
    promise: (client) => client.post('/productCarCate', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productCarCateTypes.UPDATE_PRODUCTCARCATE, productCarCateTypes.UPDATE_PRODUCTCARCATE_SUCCESS, productCarCateTypes.UPDATE_PRODUCTCARCATE_FAIL],
    promise: (client) => client.put('/productCarCate', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productCarCateTypes.DELETE_PRODUCTCARCATE, productCarCateTypes.DELETE_PRODUCTCARCATE_SUCCESS, productCarCateTypes.DELETE_PRODUCTCARCATE_FAIL],
    promise: (client) => client.del('/productCarCate/'+id, {
		token: true
    })
  };
}


