// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as productStorageQuantityTypes from '../contants/productStorageQuantity';

export function getAll(params) {
  return {
    types: [productStorageQuantityTypes.GET_ALL_PRODUCTSTORAGEQUANTITY, productStorageQuantityTypes.GET_ALL_PRODUCTSTORAGEQUANTITY_SUCCESS, productStorageQuantityTypes.GET_ALL_PRODUCTSTORAGEQUANTITY_FAIL],
    promise: (client) => client.get('/productStorageQuantity',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [productStorageQuantityTypes.GET_ONE_PRODUCTSTORAGEQUANTITY, productStorageQuantityTypes.GET_ONE_PRODUCTSTORAGEQUANTITY_SUCCESS, productStorageQuantityTypes.GET_ONE_PRODUCTSTORAGEQUANTITY_FAIL],
    promise: (client) => client.get('/productStorageQuantity/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [productStorageQuantityTypes.CREATE_PRODUCTSTORAGEQUANTITY, productStorageQuantityTypes.CREATE_PRODUCTSTORAGEQUANTITY_SUCCESS, productStorageQuantityTypes.CREATE_PRODUCTSTORAGEQUANTITY_FAIL],
    promise: (client) => client.post('/productStorageQuantity', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [productStorageQuantityTypes.UPDATE_PRODUCTSTORAGEQUANTITY, productStorageQuantityTypes.UPDATE_PRODUCTSTORAGEQUANTITY_SUCCESS, productStorageQuantityTypes.UPDATE_PRODUCTSTORAGEQUANTITY_FAIL],
    promise: (client) => client.put('/productStorageQuantity', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [productStorageQuantityTypes.DELETE_PRODUCTSTORAGEQUANTITY, productStorageQuantityTypes.DELETE_PRODUCTSTORAGEQUANTITY_SUCCESS, productStorageQuantityTypes.DELETE_PRODUCTSTORAGEQUANTITY_FAIL],
    promise: (client) => client.del('/productStorageQuantity/'+id, {
		token: true
    })
  };
}


