// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as specificationAttributeOptionTypes from '../contants/specificationAttributeOption';

export function getAll(params) {
  return {
    types: [specificationAttributeOptionTypes.GET_ALL_SPECIFICATIONATTRIBUTEOPTION, specificationAttributeOptionTypes.GET_ALL_SPECIFICATIONATTRIBUTEOPTION_SUCCESS, specificationAttributeOptionTypes.GET_ALL_SPECIFICATIONATTRIBUTEOPTION_FAIL],
    promise: (client) => client.get('/specificationAttributeOption',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [specificationAttributeOptionTypes.GET_ONE_SPECIFICATIONATTRIBUTEOPTION, specificationAttributeOptionTypes.GET_ONE_SPECIFICATIONATTRIBUTEOPTION_SUCCESS, specificationAttributeOptionTypes.GET_ONE_SPECIFICATIONATTRIBUTEOPTION_FAIL],
    promise: (client) => client.get('/specificationAttributeOption/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [specificationAttributeOptionTypes.CREATE_SPECIFICATIONATTRIBUTEOPTION, specificationAttributeOptionTypes.CREATE_SPECIFICATIONATTRIBUTEOPTION_SUCCESS, specificationAttributeOptionTypes.CREATE_SPECIFICATIONATTRIBUTEOPTION_FAIL],
    promise: (client) => client.post('/specificationAttributeOption', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [specificationAttributeOptionTypes.UPDATE_SPECIFICATIONATTRIBUTEOPTION, specificationAttributeOptionTypes.UPDATE_SPECIFICATIONATTRIBUTEOPTION_SUCCESS, specificationAttributeOptionTypes.UPDATE_SPECIFICATIONATTRIBUTEOPTION_FAIL],
    promise: (client) => client.put('/specificationAttributeOption', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [specificationAttributeOptionTypes.DELETE_SPECIFICATIONATTRIBUTEOPTION, specificationAttributeOptionTypes.DELETE_SPECIFICATIONATTRIBUTEOPTION_SUCCESS, specificationAttributeOptionTypes.DELETE_SPECIFICATIONATTRIBUTEOPTION_FAIL],
    promise: (client) => client.del('/specificationAttributeOption/'+id, {
		token: true
    })
  };
}


