// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as specificationAttributeTypes from '../contants/specificationAttribute';

export function getAll(params) {
  return {
    types: [specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE, specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE_SUCCESS, specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE_FAIL],
    promise: (client) => client.get('/specificationAttribute',{
      token: true,
      params
    })
  };
}

export function getById(id) {
  return {
    types: [specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE, specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE_SUCCESS, specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE_FAIL],
    promise: (client) => client.get('/specificationAttribute/'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE, specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE_SUCCESS, specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE_FAIL],
    promise: (client) => client.post('/specificationAttribute', {
      data: data,
	    token: true
    })
  };
}

export function update(data) {
  return {
    types: [specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE, specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE_SUCCESS, specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE_FAIL],
    promise: (client) => client.put('/specificationAttribute', {
      data: data,
	    token: true
    })
  };
}

export function remove(id) {
  return {
    types: [specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE, specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE_SUCCESS, specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE_FAIL],
    promise: (client) => client.del('/specificationAttribute/'+id, {
		token: true
    })
  };
}


