// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as userActivitiesTypes from '../contants/userActivities';

export function getAll() {
  return {
    types: [userActivitiesTypes.GET_ALL_USERACTIVITIES, userActivitiesTypes.GET_ALL_USERACTIVITIES_SUCCESS, userActivitiesTypes.GET_ALL_USERACTIVITIES_FAIL],
    promise: (client) => client.get('/userActivities',{
      token: true
    })
  };
}

export function getById(id) {
  return {
    types: [userActivitiesTypes.GET_ONE_USERACTIVITIES, userActivitiesTypes.GET_ONE_USERACTIVITIES_SUCCESS, userActivitiesTypes.GET_ONE_USERACTIVITIES_FAIL],
    promise: (client) => client.get('/userActivities'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [userActivities.CREATE_USERACTIVITIES, userActivities.CREATE_USERACTIVITIES_SUCCESS, userActivities.CREATE_USERACTIVITIES_FAIL],
    promise: (client) => client.post('/userActivities', {
      data: data,
	  token: true
    })
  };
}

export function update(id, data) {
  return {
    types: [userActivities.UPDATE_USERACTIVITIES, userActivities.UPDATE_USERACTIVITIES_SUCCESS, userActivities.UPDATE_USERACTIVITIES_FAIL],
    promise: (client) => client.put('/userActivities/'+id, {
      data: data,
	  token: true
    })
  };
}

export function delete(id) {
  return {
    types: [userActivities.DELETE_USERACTIVITIES, userActivities.DELETE_USERACTIVITIES_SUCCESS, userActivities.DELETE_USERACTIVITIES_FAIL],
    promise: (client) => client.delete('/userActivities/'+id, {
		token: true
    })
  };
}

