// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as userRoleTypes from '../contants/userRole';

export function getAll(params) {
  return {
    types: [userRoleTypes.GET_ALL_USERROLE, userRoleTypes.GET_ALL_USERROLE_SUCCESS, userRoleTypes.GET_ALL_USERROLE_FAIL],
    promise: (client) => client.get('/userRole',{
      token: true,
	  params
    })
  };
}

export function getById(id) {
  return {
    types: [userRoleTypes.GET_ONE_USERROLE, userRoleTypes.GET_ONE_USERROLE_SUCCESS, userRoleTypes.GET_ONE_USERROLE_FAIL],
    promise: (client) => client.get('/userRole'+id,{
      token: true
    })
  };
}

export function create(data) {
  return {
    types: [userRoleTypes.CREATE_USERROLE, userRoleTypes.CREATE_USERROLE_SUCCESS, userRoleTypes.CREATE_USERROLE_FAIL],
    promise: (client) => client.post('/userRole', {
      data: data,
	  token: true
    })
  };
}


export function update(data) {
  return {
    types: [userRoleTypes.UPDATE_USERROLE, userRoleTypes.UPDATE_USERROLE_SUCCESS, userRoleTypes.UPDATE_USERROLE_FAIL],
    promise: (client) => client.put('/userRole', {
      data: data,
	  token: true
    })
  };
}

export function remove(id) {
  return {
    types: [userRoleTypes.DELETE_USERROLE, userRoleTypes.DELETE_USERROLE_SUCCESS, userRoleTypes.DELETE_USERROLE_FAIL],
    promise: (client) => client.del('/userRole/'+id, {
		token: true
    })
  };
}

