// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


export const GET_ALL_JOB = 'GET_ALL_JOB';
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS';
export const GET_ALL_JOB_FAIL = 'GET_ALL_JOB_FAIL';

export const GET_ONE_JOB = 'GET_ONE_JOB';
export const GET_ONE_JOB_SUCCESS = 'GET_ONE_JOB_SUCCESS';
export const GET_ONE_JOB_FAIL = 'GET_ONE_JOB_FAIL';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

export const GET_JOB_CASCADER = 'GET_JOB_CASCADER';
export const GET_JOB_CASCADER_SUCCESS = 'GET_JOB_CASCADER_SUCCESS';
export const GET_JOB_CASCADER_FAIL = 'GET_JOB_CASCADER_FAIL';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL';

