
export const GET_ALL_MEMBER = 'GET_ALL_MEMBER';
export const GET_ALL_MEMBER_SUCCESS = 'GET_ALL_MEMBER_SUCCESS';
export const GET_ALL_MEMBER_FAIL = 'GET_ALL_MEMBER_FAIL';

export const GET_ONE_MEMBER = 'GET_ONE_MEMBER';
export const GET_ONE_MEMBER_SUCCESS = 'GET_ONE_MEMBER_SUCCESS';
export const GET_ONE_MEMBER_FAIL = 'GET_ONE_MEMBER_FAIL';

export const CREATE_MEMBER = 'CREATE_MEMBER';
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS';
export const CREATE_MEMBER_FAIL = 'CREATE_MEMBER_FAIL';

export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_FAIL = 'UPDATE_MEMBER_FAIL';

export const DELETE_MEMBER = 'DELETE_MEMBER';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAIL = 'DELETE_MEMBER_FAIL';

