export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAIL = 'GET_ALL_ORDER_FAIL';

export const GET_ONE_ORDER = 'GET_ONE_ORDER';
export const GET_ONE_ORDER_SUCCESS = 'GET_ONE_ORDER_SUCCESS';
export const GET_ONE_ORDER_FAIL = 'GET_ONE_ORDER_FAIL';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

