export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAIL = 'GET_ALL_ORDER_FAIL';

export const GET_ONE_ORDER = 'GET_ONE_ORDER';
export const GET_ONE_ORDER_SUCCESS = 'GET_ONE_ORDER_SUCCESS';
export const GET_ONE_ORDER_FAIL = 'GET_ONE_ORDER_FAIL';

export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';


