
export const GET_ALL_PRODUCTCARCATE = 'GET_ALL_PRODUCTCARCATE';
export const GET_ALL_PRODUCTCARCATE_SUCCESS = 'GET_ALL_PRODUCTCARCATE_SUCCESS';
export const GET_ALL_PRODUCTCARCATE_FAIL = 'GET_ALL_PRODUCTCARCATE_FAIL';

export const CREATE_PRODUCTCARCATE = 'CREATE_PRODUCTCARCATE';
export const CREATE_PRODUCTCARCATE_SUCCESS = 'CREATE_PRODUCTCARCATE_SUCCESS';
export const CREATE_PRODUCTCARCATE_FAIL = 'CREATE_PRODUCTCARCATE_FAIL';

export const DELETE_PRODUCTCARCATE = 'DELETE_PRODUCTCARCATE';
export const DELETE_PRODUCTCARCATE_SUCCESS = 'DELETE_PRODUCTCARCATE_SUCCESS';
export const DELETE_PRODUCTCARCATE_FAIL = 'DELETE_PRODUCTCARCATE_FAIL';

