// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface ICarCateService
    {
		Task<int> DeleteAsync(CarCate entity);

        IPagedList<CarCate> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(CarCate entity);

        Task<int> UpdateAsync(CarCate entity);

        IQueryable<CarCate> GetAll();

        Task<CarCate> FindOneAsync(int Id);	
    }
}
