// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface ICategoryService
    {
		Task<int> DeleteAsync(Category entity);

        IPagedList<Category> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(Category entity);

        Task<int> UpdateAsync(Category entity);

        IQueryable<Category> GetAll();

        Task<Category> FindOneAsync(int Id);	
    }
}
