// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
    public interface ICityCateService
    {
        Task<int> DeleteAsync(CityCate entity);

        IPagedList<CityCate> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(CityCate entity);

        Task<int> UpdateAsync(CityCate entity);

        IQueryable<CityCate> GetAll();

        Task<CityCate> FindOneAsync(int Id);
    }
}
