// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IJobService
    {
		Task<int> DeleteAsync(Job entity);

        IPagedList<Job> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(Job entity);

        Task<int> UpdateAsync(Job entity);

        IQueryable<Job> GetAll();

        Task<Job> FindOneAsync(int Id);	
    }
}
