// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IManufacturerService
    {
		Task<int> DeleteAsync(Manufacturer entity);

        IPagedList<Manufacturer> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(Manufacturer entity);

        Task<int> UpdateAsync(Manufacturer entity);

        IQueryable<Manufacturer> GetAll();

        Task<Manufacturer> FindOneAsync(int Id);	
    }
}
