// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IProductAttributeMappingService
    {
		Task<int> DeleteAsync(ProductAttributeMapping entity);

        IPagedList<ProductAttributeMapping> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(ProductAttributeMapping entity);

        Task<int> UpdateAsync(ProductAttributeMapping entity);

        IQueryable<ProductAttributeMapping> GetAll();

        Task<ProductAttributeMapping> FindOneAsync(int Id);	
    }
}
