// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IProductManufacturerService
    {
		Task<int> DeleteAsync(ProductManufacturer entity);

        IPagedList<ProductManufacturer> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(ProductManufacturer entity);

        Task<int> UpdateAsync(ProductManufacturer entity);

        IQueryable<ProductManufacturer> GetAll();

        Task<ProductManufacturer> FindOneAsync(int Id);	
    }
}
