// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface ISmsCodeService
    {
		Task<int> DeleteAsync(SmsCode entity);

        IPagedList<SmsCode> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(SmsCode entity);

        Task<int> UpdateAsync(SmsCode entity);

        IQueryable<SmsCode> GetAll();

        Task<SmsCode> FindOneAsync(int Id);	
    }
}
