// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface ISpecificationAttributeOptionService
    {
		Task<int> DeleteAsync(SpecificationAttributeOption entity);

        IPagedList<SpecificationAttributeOption> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(SpecificationAttributeOption entity);

        Task<int> UpdateAsync(SpecificationAttributeOption entity);

        IQueryable<SpecificationAttributeOption> GetAll();

        Task<SpecificationAttributeOption> FindOneAsync(int Id);	
    }
}
