// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IStorageService
    {
		Task<int> DeleteAsync(Storage entity);

        IPagedList<Storage> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(Storage entity);

        Task<int> UpdateAsync(Storage entity);

        IQueryable<Storage> GetAll();

        Task<Storage> FindOneAsync(int Id);	
    }
}
