// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IUserPermissionService
    {
		Task<int> DeleteAsync(UserPermission entity);

        IPagedList<UserPermission> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(UserPermission entity);

        Task<int> UpdateAsync(UserPermission entity);

        IQueryable<UserPermission> GetAll();

        Task<UserPermission> FindOneAsync(int Id);	
    }
}
