// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
    public class AddressDTO
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string CityCode { get; set; }
        public string CityCodeList { get; set; }
        public string Province { get; set; }
        public string Area { get; set; }
        public string County { get; set; }
        public string Detail { get; set; }
        public Boolean Default { get; set; }
        public int Id { get; set; }
    }
}
