// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
    public class CityCateDTO
    {

        public string Name { get; set; }
        public string ParentCode { get; set; }

        public string Code { get; set; }
        public int DisplayOrder { get; set; }

        public int Level { get; set; }

        public string PinYin { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }
        public int Id { get; set; }
    }
}
