// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
    public class ManufacturerDTO
    {

        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int Id { get; set; }

        public bool IsHot { get; set; }

        public int HotOrder { get; set; }
    }
}
