// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
	public class OrderItemDTO
    {
         
       public Guid OrderItemGuid  { get; set; } 
       public int OrderId  { get; set; } 
       public int ProductId  { get; set; } 
       public int Quantity  { get; set; } 
       public Decimal UnitPrice  { get; set; } 
       public Decimal Price  { get; set; } 
       public string AttributeDescription  { get; set; } 
       public string AttributesXml  { get; set; } 
       public int Id  { get; set; } 
    }
}
