// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;
using System.Collections.Generic;

namespace MB.Data.DTO
{
    public class ProductDTO
    {
        public string OwnerId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string SKU { get; set; }
        public Boolean isAgreeActive { get; set; }
        public int ManufacturerId { get; set; }
        public bool IsFeaturedProduct { get; set; }
        public int Status { get; set; }
        public Decimal Price { get; set; }
        public Decimal VipPrice { get; set; }
        public string ImageUrl { get; set; }
        public decimal UrgencyPrice { get; set; }
        public string Description { get; set; }
        public string DetailUrl { get; set; }
        public int Id { get; set; }
        public int SoldCount { get; set; }
        public int Hot { get; set; }
    }
}
