
// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
    public class ProductCarCateDTO
    {

        public int ProductId { get; set; }

        public int CarCateId { get; set; }

        public int Id { get; set; }
    }
}
