// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
	public class ProductDTO
    {
         
       public string Name  { get; set; } 
       public int CategoryId  { get; set; } 
       public string SKU  { get; set; } 
       public Boolean isAgreeActive  { get; set; } 
       public int Status  { get; set; } 
       public Decimal Price  { get; set; } 
       public Decimal VipPrice  { get; set; } 
       public string ImageUrl  { get; set; } 
       public int Id  { get; set; } 
    }
}
