// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;
using System.Data.Entity.Spatial;

namespace MB.Data.DTO
{
    public class StorageDTO
    {

        public string Name { get; set; }

        public string Address { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Distance { get; set; }

        public int Id { get; set; }
    }
}
