// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;
using FluentValidation.Attributes;
using System.ComponentModel.DataAnnotations;
using MB.Data.Validator;

namespace MB.Data.DTO
{
    [Validator(typeof(UserPermissionValidator))]
    public class UserPermissionDTO
    {

        public string Name { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }

        public string Group { get; set; }
        public Boolean IsApi { get; set; }
        public int Id { get; set; }
    }
}
