// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as addressTypes from '../contants/address';

const initialState = {
  loaded: false,
  entity: {}
};

export default function address(state = initialState, action = {}) {
  switch (action.type) {
    case addressTypes.GET_ALL_ADDRESS:
    case addressTypes.GET_ONE_ADDRESS:
    case addressTypes.CREATE_ADDRESS:
    case addressTypes.UPDATE_ADDRESS:
    case addressTypes.DELETE_ADDRESS:
      return {
        ...state,
        loading: true
      };
    case addressTypes.GET_ALL_ADDRESS_FAIL:
    case addressTypes.GET_ONE_ADDRESS_FAIL:
    case addressTypes.CREATE_ADDRESS_FAIL:
    case addressTypes.UPDATE_ADDRESS_FAIL:
    case addressTypes.DELETE_ADDRESS_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case addressTypes.GET_ALL_ADDRESS_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case addressTypes.GET_ONE_ADDRESS_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case addressTypes.CREATE_ADDRESS_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case addressTypes.UPDATE_ADDRESS_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case addressTypes.DELETE_ADDRESS_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

