// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as orderItemTypes from '../contants/orderItem';

const initialState = {
  loaded: false,
  entity: {}
};

export default function orderItem(state = initialState, action = {}) {
  switch (action.type) {
    case orderItemTypes.GET_ALL_ORDERITEM:
    case orderItemTypes.GET_ONE_ORDERITEM:
    case orderItemTypes.CREATE_ORDERITEM:
    case orderItemTypes.UPDATE_ORDERITEM:
    case orderItemTypes.DELETE_ORDERITEM:
      return {
        ...state,
        loading: true
      };
    case orderItemTypes.GET_ALL_ORDERITEM_FAIL:
    case orderItemTypes.GET_ONE_ORDERITEM_FAIL:
    case orderItemTypes.CREATE_ORDERITEM_FAIL:
    case orderItemTypes.UPDATE_ORDERITEM_FAIL:
    case orderItemTypes.DELETE_ORDERITEM_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case orderItemTypes.GET_ALL_ORDERITEM_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case orderItemTypes.GET_ONE_ORDERITEM_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case orderItemTypes.CREATE_ORDERITEM_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case orderItemTypes.UPDATE_ORDERITEM_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case orderItemTypes.DELETE_ORDERITEM_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

