// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productAttributeCategoryMappingTypes from '../contants/productAttributeCategoryMapping';

const initialState = {
  loaded: false,
  entity: {}
};

export default function productAttributeCategoryMapping(state = initialState, action = {}) {
  switch (action.type) {
    case productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING:
    case productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING:
    case productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING:
    case productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING:
    case productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING:
      return {
        ...state,
        loading: true
      };
    case productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL:
    case productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL:
    case productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL:
    case productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL:
    case productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productAttributeCategoryMappingTypes.GET_ALL_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productAttributeCategoryMappingTypes.GET_ONE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeCategoryMappingTypes.CREATE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeCategoryMappingTypes.UPDATE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeCategoryMappingTypes.DELETE_PRODUCTATTRIBUTECATEGORYMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

