// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;
using MB.Helpers;

using MB.Filters;

namespace MB.Controllers
{
    [MbAuthorize]
    [RoutePrefix("api/Manufacturer")]
    public class ManufacturerController : ApiController
    {
        private IManufacturerService ManufacturerService;
        public ManufacturerController(
            IManufacturerService _ManufacturerService
          )
        {
            this.ManufacturerService = _ManufacturerService;
        }

        [Route("")]
        public ApiListResult<ManufacturerDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = ManufacturerService.GetAll().Where(x => !x.Deleted).ProjectTo<ManufacturerDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<ManufacturerDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<ManufacturerDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(ManufacturerDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            ManufacturerDTO Manufacturer = await ManufacturerService.GetAll().Where(x => x.Id == id && !x.Deleted).ProjectTo<ManufacturerDTO>().FirstOrDefaultAsync();
            if (Manufacturer == null)
            {
                return NotFound();
            }
            return Ok(Manufacturer);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(ManufacturerDTO))]
        public async Task<IHttpActionResult> Create([FromBody]ManufacturerDTO ManufacturerDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = ManufacturerDto.ToEntity();

            entity.CreateUserId = User.Identity.GetUserId();
            entity.CreateTime = DateTime.Now;
            await ManufacturerService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(ManufacturerDTO))]
        public async Task<IHttpActionResult> Update([FromBody]ManufacturerDTO ManufacturerDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await ManufacturerService.FindOneAsync(ManufacturerDto.Id);
            entity = ManufacturerDto.ToEntity(entity);
            entity.LastUserId = User.Identity.GetUserId();
            entity.LastTime = DateTime.Now;
            await ManufacturerService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(ManufacturerDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            Manufacturer entity = await ManufacturerService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await ManufacturerService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

        [Route("selectlist")]
        [HttpGet]
        public List<ManufacturerDTO> GetSelectList()
        {
            var result = new List<ManufacturerDTO>();
            var roleId = MBHelper.GetUserRoleId(User);
            result = ManufacturerService.GetAll().Where(x => !x.Deleted).ProjectTo<ManufacturerDTO>().ToList();
            return result;
        }

    }
}




