// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

namespace MB.Controllers
{
    [RoutePrefix("api/ProductAttributeCategoryMapping")]
    public class ProductAttributeCategoryMappingController : ApiController
    {
        private IProductAttributeCategoryMappingService ProductAttributeCategoryMappingService;
        public ProductAttributeCategoryMappingController(
            IProductAttributeCategoryMappingService _ProductAttributeCategoryMappingService
          )
        {
            this.ProductAttributeCategoryMappingService = _ProductAttributeCategoryMappingService;
        }

        [Route("")]
        public ApiListResult<ProductAttributeCategoryMappingDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = ProductAttributeCategoryMappingService.GetAll().ProjectTo<ProductAttributeCategoryMappingDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<ProductAttributeCategoryMappingDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<ProductAttributeCategoryMappingDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(ProductAttributeCategoryMappingDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            ProductAttributeCategoryMappingDTO ProductAttributeCategoryMapping = await ProductAttributeCategoryMappingService.GetAll().Where(x => x.Id == id ).ProjectTo<ProductAttributeCategoryMappingDTO>().FirstOrDefaultAsync();
            if (ProductAttributeCategoryMapping == null)
            {
                return NotFound();
            }
            return Ok(ProductAttributeCategoryMapping);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(ProductAttributeCategoryMappingDTO))]
        public async Task<IHttpActionResult> Create([FromBody]ProductAttributeCategoryMappingDTO ProductAttributeCategoryMappingDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = ProductAttributeCategoryMappingDto.ToEntity();

          
            await ProductAttributeCategoryMappingService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(ProductAttributeCategoryMappingDTO))]
        public async Task<IHttpActionResult> Update([FromBody]ProductAttributeCategoryMappingDTO ProductAttributeCategoryMappingDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await ProductAttributeCategoryMappingService.FindOneAsync(ProductAttributeCategoryMappingDto.Id);
            entity = ProductAttributeCategoryMappingDto.ToEntity(entity);
           
            await ProductAttributeCategoryMappingService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(ProductAttributeCategoryMappingDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            ProductAttributeCategoryMapping entity = await ProductAttributeCategoryMappingService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await ProductAttributeCategoryMappingService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




