// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

using MB.Filters;

namespace MB.Controllers
{
    [MbAuthorize]
    [RoutePrefix("api/ProductStorageQuantity")]
    public class ProductStorageQuantityController : ApiController
    {
        private IProductStorageQuantityService ProductStorageQuantityService;
        public ProductStorageQuantityController(
            IProductStorageQuantityService _ProductStorageQuantityService
          )
        {
            this.ProductStorageQuantityService = _ProductStorageQuantityService;
        }

        [Route("")]
        public ApiListResult<ProductStorageQuantityDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = ProductStorageQuantityService.GetAll().Where(x=>x.ProductId==option.Id).ProjectTo<ProductStorageQuantityDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<ProductStorageQuantityDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<ProductStorageQuantityDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(ProductStorageQuantityDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            ProductStorageQuantityDTO ProductStorageQuantity = await ProductStorageQuantityService.GetAll().Where(x => x.Id == id ).ProjectTo<ProductStorageQuantityDTO>().FirstOrDefaultAsync();
            if (ProductStorageQuantity == null)
            {
                return NotFound();
            }
            return Ok(ProductStorageQuantity);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(ProductStorageQuantityDTO))]
        public async Task<IHttpActionResult> Create([FromBody]ProductStorageQuantityDTO ProductStorageQuantityDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = ProductStorageQuantityDto.ToEntity();

            entity.CreateUserId = User.Identity.GetUserId();
            entity.CreateTime = DateTime.Now;
            await ProductStorageQuantityService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(ProductStorageQuantityDTO))]
        public async Task<IHttpActionResult> Update([FromBody]ProductStorageQuantityDTO ProductStorageQuantityDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await ProductStorageQuantityService.FindOneAsync(ProductStorageQuantityDto.Id);
            entity = ProductStorageQuantityDto.ToEntity(entity);
            entity.LastUserId = User.Identity.GetUserId();
            entity.LastTime = DateTime.Now;
            await ProductStorageQuantityService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(ProductStorageQuantityDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            ProductStorageQuantity entity = await ProductStorageQuantityService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await ProductStorageQuantityService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




