// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

namespace MB.Controllers
{
    [RoutePrefix("api/ProductCarCate")]
    public class ProductCarCateController : ApiController
    {
        private IProductCarCateService ProductCarCateService;
        public ProductCarCateController(
            IProductCarCateService _ProductCarCateService
          )
        {
            this.ProductCarCateService = _ProductCarCateService;
        }

        [Route("")]
        public ApiListResult<ProductCarCateDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = ProductCarCateService.GetAll().Where(x => x.ProductId == option.Id).ProjectTo<ProductCarCateDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<ProductCarCateDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<ProductCarCateDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(ProductCarCateDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            ProductCarCateDTO ProductCarCate = await ProductCarCateService.GetAll().Where(x => x.Id == id).ProjectTo<ProductCarCateDTO>().FirstOrDefaultAsync();
            if (ProductCarCate == null)
            {
                return NotFound();
            }
            return Ok(ProductCarCate);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(ProductCarCateDTO))]
        public async Task<IHttpActionResult> Create([FromBody]ProductCarCateDTO ProductCarCateDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = ProductCarCateDto.ToEntity();


            await ProductCarCateService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(ProductCarCateDTO))]
        public async Task<IHttpActionResult> Update([FromBody]ProductCarCateDTO ProductCarCateDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await ProductCarCateService.FindOneAsync(ProductCarCateDto.Id);
            entity = ProductCarCateDto.ToEntity(entity);
           
            await ProductCarCateService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(ProductCarCateDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            ProductCarCate entity = await ProductCarCateService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await ProductCarCateService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




