// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

namespace MB.Controllers
{
    [RoutePrefix("api/SpecificationAttributeOption")]
    public class SpecificationAttributeOptionController : ApiController
    {
        private ISpecificationAttributeOptionService SpecificationAttributeOptionService;
        public SpecificationAttributeOptionController(
            ISpecificationAttributeOptionService _SpecificationAttributeOptionService
          )
        {
            this.SpecificationAttributeOptionService = _SpecificationAttributeOptionService;
        }

        [Route("")]
        public ApiListResult<SpecificationAttributeOptionDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = SpecificationAttributeOptionService.GetAll().Where(x => !x.Deleted).ProjectTo<SpecificationAttributeOptionDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<SpecificationAttributeOptionDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<SpecificationAttributeOptionDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(SpecificationAttributeOptionDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            SpecificationAttributeOptionDTO SpecificationAttributeOption = await SpecificationAttributeOptionService.GetAll().Where(x => x.Id == id && !x.Deleted).ProjectTo<SpecificationAttributeOptionDTO>().FirstOrDefaultAsync();
            if (SpecificationAttributeOption == null)
            {
                return NotFound();
            }
            return Ok(SpecificationAttributeOption);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(SpecificationAttributeOptionDTO))]
        public async Task<IHttpActionResult> Create([FromBody]SpecificationAttributeOptionDTO SpecificationAttributeOptionDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = SpecificationAttributeOptionDto.ToEntity();

            entity.CreateUserId = User.Identity.GetUserId();
            entity.CreateTime = DateTime.Now;
            await SpecificationAttributeOptionService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(SpecificationAttributeOptionDTO))]
        public async Task<IHttpActionResult> Update([FromBody]SpecificationAttributeOptionDTO SpecificationAttributeOptionDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await SpecificationAttributeOptionService.FindOneAsync(SpecificationAttributeOptionDto.Id);
            entity = SpecificationAttributeOptionDto.ToEntity(entity);
            entity.LastUserId = User.Identity.GetUserId();
            entity.LastTime = DateTime.Now;
            await SpecificationAttributeOptionService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(SpecificationAttributeOptionDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            SpecificationAttributeOption entity = await SpecificationAttributeOptionService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await SpecificationAttributeOptionService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




