// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;

using MB.Filters;

namespace MB.Controllers
{
    [MbAuthorize]
    [RoutePrefix("api/SpecificationAttribute")]
    public class SpecificationAttributeController : ApiController
    {
        private ISpecificationAttributeService SpecificationAttributeService;
        public SpecificationAttributeController(
            ISpecificationAttributeService _SpecificationAttributeService
          )
        {
            this.SpecificationAttributeService = _SpecificationAttributeService;
        }

        [Route("")]
        public ApiListResult<SpecificationAttributeDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = SpecificationAttributeService.GetAll().ProjectTo<SpecificationAttributeDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<SpecificationAttributeDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<SpecificationAttributeDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(SpecificationAttributeDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            SpecificationAttributeDTO SpecificationAttribute = await SpecificationAttributeService.GetAll().Where(x => x.Id == id ).ProjectTo<SpecificationAttributeDTO>().FirstOrDefaultAsync();
            if (SpecificationAttribute == null)
            {
                return NotFound();
            }
            return Ok(SpecificationAttribute);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(SpecificationAttributeDTO))]
        public async Task<IHttpActionResult> Create([FromBody]SpecificationAttributeDTO SpecificationAttributeDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = SpecificationAttributeDto.ToEntity();


            await SpecificationAttributeService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(SpecificationAttributeDTO))]
        public async Task<IHttpActionResult> Update([FromBody]SpecificationAttributeDTO SpecificationAttributeDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await SpecificationAttributeService.FindOneAsync(SpecificationAttributeDto.Id);
            entity = SpecificationAttributeDto.ToEntity(entity);
          
            await SpecificationAttributeService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(SpecificationAttributeDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            SpecificationAttribute entity = await SpecificationAttributeService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await SpecificationAttributeService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}




