// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using System.Web.Http.Description;
using Microsoft.AspNet.Identity;
using MB.Data.Service;
using MB.Data.DTO;
using MB.Data.AutoMapper;
using MB.Data.Models;
using AutoMapper.QueryableExtensions;
using System.Threading.Tasks;
using SQ.Core.Data;



namespace MB.Controllers
{
    [RoutePrefix("api/UserPermission")]
    public class UserPermissionController : ApiController
    {
        private IUserPermissionService UserPermissionService;
        public UserPermissionController(
            IUserPermissionService _UserPermissionService
          )
        {
            this.UserPermissionService = _UserPermissionService;
        }

        [Route("")]
        public ApiListResult<UserPermissionDTO> Get([FromUri] AntPageOption option = null)
        {
            var query = UserPermissionService.GetAll().Where(x => !x.Deleted).ProjectTo<UserPermissionDTO>();
            if (option != null)
            {
                if (!string.IsNullOrEmpty(option.SortField))
                {
                    //for example
                    if (option.SortField == "id")
                    {
                        if (option.SortOrder == PageSortTyoe.DESC)
                        {
                            query = query.OrderByDescending(x => x.Id);
                        }
                        else
                        {
                            query = query.OrderBy(x => x.Id);
                        }
                    }
                }

                if (option.Page > 0 && option.Results > 0)
                {
                    if (string.IsNullOrEmpty(option.SortField))
                    {
                        query = query.OrderBy(x => x.Id);
                    }
                }
            }
            else
            {
                query = query.OrderBy(x => x.Id);
            }
            var count = query.Count();
            var result = query.Paging<UserPermissionDTO>(option.Page - 1, option.Results, count);
            return new ApiListResult<UserPermissionDTO>(result, result.PageIndex, result.PageSize, count);
        }

        [Route("{id:int}")]
        [ResponseType(typeof(UserPermissionDTO))]
        public async Task<IHttpActionResult> GetById(int id)
        {
            UserPermissionDTO UserPermission = await UserPermissionService.GetAll().Where(x => x.Id == id && !x.Deleted).ProjectTo<UserPermissionDTO>().FirstOrDefaultAsync();
            if (UserPermission == null)
            {
                return NotFound();
            }
            return Ok(UserPermission);
        }

        [Route("")]
        [HttpPost]
        [ResponseType(typeof(UserPermissionDTO))]
        public async Task<IHttpActionResult> Create([FromBody]UserPermissionDTO UserPermissionDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var entity = UserPermissionDto.ToEntity();

            entity.CreateUserId = User.Identity.GetUserId();
            entity.CreateTime = DateTime.Now;
            await UserPermissionService.InsertAsync(entity);
            return Ok(entity.ToModel());
        }


        [Route("")]
        [HttpPut]
        [ResponseType(typeof(UserPermissionDTO))]
        public async Task<IHttpActionResult> Update([FromBody]UserPermissionDTO UserPermissionDto)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var entity = await UserPermissionService.FindOneAsync(UserPermissionDto.Id);
            entity = UserPermissionDto.ToEntity(entity);
            entity.LastUserId = User.Identity.GetUserId();
            entity.LastTime = DateTime.Now;
            await UserPermissionService.UpdateAsync(entity);
            return Ok(entity.ToModel());
        }

        [Route("{id:int}")]
        [HttpDelete]
        [ResponseType(typeof(UserPermissionDTO))]
        public async Task<IHttpActionResult> Delete(int id)
        {
            UserPermission entity = await UserPermissionService.FindOneAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            await UserPermissionService.DeleteAsync(entity);

            return Ok(entity.ToModel());
        }

    }
}

