// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using SQ.Core.Data;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Service
{
	public interface IOrderItemService
    {
		Task<int> DeleteAsync(OrderItem entity);

        IPagedList<OrderItem> GetPageList(int pageIndex, int pageSize);

        Task<int> InsertAsync(OrderItem entity);

        Task<int> UpdateAsync(OrderItem entity);

        IQueryable<OrderItem> GetAll();

        Task<OrderItem> FindOneAsync(int Id);	
    }
}
