// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
	public class AddressDTO
    {
         
       public string Name  { get; set; } 
       public string PhoneNumber  { get; set; } 
       public int CityId  { get; set; } 
       public CityCate CityCate  { get; set; } 
       public string Detail  { get; set; } 
       public Boolean Default  { get; set; } 
       public int Id  { get; set; } 
    }
}
