// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using MB.Data.Models;

namespace MB.Data.DTO
{
	public class BannerDTO
    {
         
       public string Url  { get; set; } 
       public string ImageUrl  { get; set; } 
       public Boolean NativeRoute  { get; set; } 
       public int DisplayOrder  { get; set; } 
       public int Status  { get; set; } 
       public int Id  { get; set; } 
    }
}
