// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import React, { Component } from 'react';
import { bindActionCreators } from 'redux';
import { Link } from 'react-router';
import { connect } from 'react-redux'
import { Spin, Table, Icon, Button, Modal, Form, Input, Checkbox, message,Select } from 'antd';
import connectStatic from '../utils/connectStatic'
import * as authActions from '../actions/auth'
import * as productActions from '../actions/product'
import * as productAttributeActions from '../actions/productAttribute'
import * as productAttributeMappingActions from '../actions/productAttributeMapping'
import _ from 'lodash';
const FormItem = Form.Item;
const createForm = Form.create;
const confirm = Modal.confirm;
const Option = Select.Option;

var ProductAttributeMapping = React.createClass({

  displayName: 'ProductAttributeMapping',

  getInitialState() {
    return {
      pagination: {
        pageSize: 10,
        current: 1
      }
    };
  },

  fetchData(page){
    const {routeParams:{id}}=this.props;
    var promise=[];
    promise.push(this.props.productActions.getById(id));
    promise.push(this.props.productAttributeActions.getSelectList());
    Promise.all(promise).then(err=>{
      this.props.productAttributeMappingActions.getAll({
        id,
        results: this.state.pagination.pageSize,
        page: page || this.state.pagination.current
      });
    })
  },

  componentDidMount(){
    this.fetchData();
  },

  handleTableChange(pagination, filters, sorter) {
    const pager = this.state.pagination;
    const {routeParams:{id}}=this.props;
    pager.current = pagination.current;
    this.setState({
      pagination: pager
    });
    this.props.productAttributeMappingActions.getAll({
      id,
      results: pagination.pageSize,
      page: pagination.current,
      sortField: sorter.field,
      sortOrder: sorter.order
    });
  },
  onAdd(){
    this.setState({
      visible: true,
      edit: false,
      title: '添加ProductAttributeMapping',
      record: {}
    });
  },

  onEdit(record){
    this.props.productAttributeMappingActions.getById(record.id).then((err)=> {
      if (err) {
        message.error('获取ProductAttributeMapping数据失败！请刷新页面尝试。');
      }
      else {
        this.setState({
          visible: true,
          edit: true,
          title: '编辑ProductAttributeMapping'
        });
      }
    });
  },

  onRemove(record){
    const self = this;
    const { productAttributeMapping:{ list }} = this.props;
    let source = list.data;
    const remove = this.props.productAttributeMappingActions.remove;
    confirm({
      title: '确认删除该ProductAttributeMapping？',
      onOk() {
        remove(record.id).then((err)=> {
          if (err) {
            message.error('删除操作执行失败！请刷新页面尝试。');
          } else {
            message.success('删除操作执行成功！');
            let data = _.remove(source, (item)=> {
              return item.id === record.id
            });
            let page = self.state.pagination.current;
            if (data.length === 0) {
              page = page - 1;
            }
            self.fetchData(_.max([page - 1, 1]));
          }
        });
      },
      onCancel() {
      }
    });
  },

  onModalSubmit(){
    const { edit }=this.state;
    const {routeParams:{id}}=this.props;
    const { update, create} =this.props.productAttributeMappingActions;
    const { entity }= this.props.productAttributeMapping;
    this.props.form.validateFields((errors, formdata) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        return;
      }
      formdata.productId=id;
      if (edit) {
        formdata.id = entity.id;
        update(formdata).then((err)=> {
          if (err) {
            message.error('更新数据失败。');
          } else {
            message.success('更新数据成功！');
            this.props.form.resetFields();
            this.fetchData();
          }
        });
      } else {
        create(formdata).then((err)=> {
          if (err) {
            message.error('创建数据失败。');
          } else {
            message.success('创建数据成功！');
            this.props.form.resetFields();
            this.fetchData();
          }
        });
      }
      this.onModalClose();
    });
  },

  onModalClose(){
    this.setState({visible: false}, ()=> {
      this.props.form.resetFields();
    });
  },

  render() {
    const { selectlist }= this.props.productAttribute;
    const columns = [{
      title: 'Id',
      dataIndex: 'id',
      sorter: true,
      width: '20%'
    }, {
      title: '属性名',
      dataIndex: 'productAttributeId',
      render: (productAttributeId)=> selectlist.find(x=>x.id==productAttributeId).name
   
    },{
      title: '操作',
      key: 'operation',
      render: (text, record) => (
        <span>
          <Button type="ghost" shape="circle" icon="edit" size="small" title='编辑'
                  onClick={this.onEdit.bind(null,record)}/>
          <span className="ant-divider"></span>
          <Button type="ghost" shape="circle" icon="delete" size="small" title='删除'
                  onClick={this.onRemove.bind(null,record)}/>
        </span>
      )
    }];
    const { productAttributeMapping:{ loading, list, entity }} = this.props;
    const product = this.props.product.entity;
    const { title, visible, edit }=this.state;

    const data = list ? list.data : [];
    const pagination = Object.assign({}, this.state.pagination, {total: list ? list.recordCount : 0})
    const { getFieldProps } = this.props.form;
    const record = edit ? entity : {};
    const formItemLayout = {
      labelCol: {span: 4},
      wrapperCol: {span: 20}
    };
    return (
      <div className='container'>
        <div className='ant-list-header' data-flex="main:justify">
          <div>
            <Link to='product'>
              <Icon type='arrow-left'/> 返回列表
            </Link>
          </div>
          <div className='ant-list-header-right'>
            <Button type="primary" icon="plus" onClick={this.onAdd}>添加产品属性</Button>
          </div>
        </div>
        <div className='nav-tabs-container'>
          <ul className="nav nav-tabs">
            <li ><Link to={`product/update/${product.id}`} >基本信息</Link></li>
            <li><Link to={`productstoragequantity/${product.id}`} >管理库存</Link></li>
            <li><Link to={`productcarcate/${product.id}`} >车型匹配</Link></li>  
            <li className="active"><a>产品属性</a></li>  
          </ul>
        </div>
        <Table
          ref='table'
          columns={columns}
          rowKey={record => record.id}
          dataSource={data}
          pagination={pagination}
          loading={loading}
          onChange={this.handleTableChange}
          />
        <Modal title={title} visible={visible} onOk={this.onModalSubmit}
               onCancel={this.onModalClose}>
          <Form horizontal>
            <FormItem
              {...formItemLayout}
              label="产品属性"
              >
              <Select {...getFieldProps('productAttributeId', {
                  initialValue: record.productAttributeId?`${record.productAttributeId}`:'',
                  rules: [{required: true, message: '请选择产品属性'}]
                }
              )} placeholder='请选择产品属性' >
                {selectlist.map(item=>{
                  return (
                    <Option key={item.id} >{item.name}</Option>
                  )
                })}
              </Select>
            </FormItem>

          </Form>
        </Modal>
      </div>
    );
  }
});

function mapStateToProps(state) {
  return {
    auth: state.auth,
    productAttributeMapping: state.productAttributeMapping,
    productAttribute: state.productAttribute,
    product: state.product
  }
}

function mapDispatchToProps(dispatch) {
  return {
    authActions: bindActionCreators(authActions, dispatch),
    productActions: bindActionCreators(productActions, dispatch),
    productAttributeActions: bindActionCreators(productAttributeActions, dispatch),
    productAttributeMappingActions: bindActionCreators(productAttributeMappingActions, dispatch)
  
  }
}

const statics = {
  path: 'productattributemapping',
  menuGroup: 'product',
  breadcrumb: [{
    title: '产品中心'
  }, {
    title: '关联产品属性'
  }]
};

ProductAttributeMapping = createForm()(ProductAttributeMapping);

export default connectStatic(statics)(connect(mapStateToProps, mapDispatchToProps)(ProductAttributeMapping))
