// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import React, { Component } from 'react';
import { bindActionCreators } from 'redux';
import { Link } from 'react-router';
import { connect } from 'react-redux'
import { Spin, Table, Icon, Button, Modal, Form, Input, Checkbox, message,Select } from 'antd';
import connectStatic from '../utils/connectStatic'
import * as authActions from '../actions/auth'
import * as productActions from '../actions/product'
import * as productAttributeActions from '../actions/productAttribute'
import * as productAttributeValueActions from '../actions/productAttributeValue'
import * as productAttributeMappingActions from '../actions/productAttributeMapping'
import ProductAttributeValueForm from '../components/form/ProductAttributeValueForm';
import _ from 'lodash';
const FormItem = Form.Item;
const createForm = Form.create;
const confirm = Modal.confirm;
const Option = Select.Option;

var ProductAttributeMapping = React.createClass({

  displayName: 'ProductAttributeMapping',

  getInitialState() {
    return {
      pagination: {
        pageSize: 10,
        current: 1
      },
      valuePagination: {
        pageSize: 20,
        current: 1
      }
    };
  },

  fetchData(page){
    const {routeParams:{id}}=this.props;
    var promise = [];
    promise.push(this.props.productActions.getById(id));
    promise.push(this.props.productAttributeActions.getSelectList());
    Promise.all(promise).then(err=> {
      this.props.productAttributeMappingActions.getAll({
        id,
        results: this.state.pagination.pageSize,
        page: page || this.state.pagination.current
      });
    })
  },

  componentDidMount(){
    this.fetchData();
  },

  handleTableChange(pagination, filters, sorter) {
    const pager = this.state.pagination;
    const {routeParams:{id}}=this.props;
    pager.current = pagination.current;
    this.setState({
      pagination: pager
    });
    this.props.productAttributeMappingActions.getAll({
      id,
      results: pagination.pageSize,
      page: pagination.current,
      sortField: sorter.field,
      sortOrder: sorter.order
    });
  },
  handleValueTableChange(pagination, filters, sorter){
    const pager = this.state.valuePagination;
    const {routeParams:{id}}=this.props;
    pager.current = pagination.current;
    this.setState({
      valuePagination: pager
    });
    this.props.productAttributeValueActions.getAll({
      id,
      results: pagination.pageSize,
      page: pagination.current,
      sortField: sorter.field,
      sortOrder: sorter.order
    });
  },

  onAdd(){
    this.setState({
      visible: true,
      edit: false,
      title: '添加产品属性',
      record: {}
    });
  },

  onEdit(record){
    this.props.productAttributeMappingActions.getById(record.id).then((err)=> {
      if (err) {
        message.error('获取产品属性数据失败！请刷新页面尝试。');
      }
      else {
        this.setState({
          visible: true,
          edit: true,
          title: '编辑产品属性'
        });
      }
    });
  },

  onRemove(record){
    const self = this;
    const { productAttributeMapping:{ list }} = this.props;
    let source = list.data;
    const remove = this.props.productAttributeMappingActions.remove;
    confirm({
      title: '确认删除该产品属性？',
      onOk() {
        remove(record.id).then((err)=> {
          if (err) {
            message.error('删除操作执行失败！请刷新页面尝试。');
          } else {
            message.success('删除操作执行成功！');
            let data = _.remove(source, (item)=> {
              return item.id === record.id
            });
            let page = self.state.pagination.current;
            if (data.length === 0) {
              page = page - 1;
            }
            self.fetchData(_.max([page - 1, 1]));
          }
        });
      },
      onCancel() {
      }
    });
  },

  onModalSubmit(){
    const { edit }=this.state;
    const {routeParams:{id}}=this.props;
    const { update, create} =this.props.productAttributeMappingActions;
    const { entity }= this.props.productAttributeMapping;
    this.props.form.validateFields((errors, formdata) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        return;
      }
      formdata.productId = id;
      if (edit) {
        formdata.id = entity.id;
        update(formdata).then((err)=> {
          if (err) {
            message.error('更新数据失败。');
          } else {
            message.success('更新数据成功！');
            this.props.form.resetFields();
            this.fetchData();
          }
        });
      } else {
        create(formdata).then((err)=> {
          if (err) {
            message.error('创建数据失败。');
          } else {
            message.success('创建数据成功！');
            this.props.form.resetFields();
            this.fetchData();
          }
        });
      }
      this.onModalClose();
    });
  },

  onModalClose(){
    this.setState({visible: false}, ()=> {
      this.props.form.resetFields();
    });
  },

  onValueModalClose(){
    this.setState({showValueModal: false});
  },

  fetchModalData(id, page){
    return this.props.productAttributeValueActions.getAll({
      id,
      results: this.state.valuePagination.pageSize,
      page: page || this.state.valuePagination.current
    })
  },

  onShowValueModal(productAttributeMappingId, name){
    this.fetchModalData(productAttributeMappingId).then(err=> {
      if (err) {
        message.error('获取产品属性数据失败！请刷新页面尝试。');
      }
      else {
        this.setState({
          showValueModal: true,
          valueTitle: `产品${name}列表`,
          productAttributeMappingId
        });
      }
    });
  },

  onAddValue(){
    this.setState({
      showValueEditModal: true,
      edit: false,
      title: '添加属性值',
      record: {}
    });
  },

  onEditValue(record){
    this.props.productAttributeValueActions.getById(record.id).then((err)=> {
      if (err) {
        message.error('获取产品属性值数据失败！请刷新页面尝试。');
      }
      else {
        this.setState({
          showValueEditModal: true,
          edit: true,
          title: '编辑属性值'
        });
      }
    });
  },

  onRemoveValue(record){
    const self = this;
    const { productAttributeMappingId }=this.state;
    const { productAttributeValue:{ list }} = this.props;
    let source = list.data;
    const remove = this.props.productAttributeValueActions.remove;
    confirm({
      title: '确认删除该产品属性？',
      onOk() {
        remove(record.id).then((err)=> {
          if (err) {
            message.error('删除操作执行失败！请刷新页面尝试。');
          } else {
            message.success('删除操作执行成功！');
            let data = _.remove(source, (item)=> {
              return item.id === record.id
            });
            let page = self.state.valuePagination.current;
            if (data.length === 0) {
              page = page - 1;
            }
            self.fetchModalData(productAttributeMappingId, _.max([page - 1, 1]));
          }
        });
      },
      onCancel() {
      }
    });
  },

  onValueSubmit(){
    const { edit, productAttributeMappingId }=this.state;
    const { update, create} =this.props.productAttributeValueActions;
    const { entity }= this.props.productAttributeValue;
    this.refs.pavf.validateFields((errors, formdata) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        return;
      }
      formdata.productAttributeMappingId = productAttributeMappingId;
      if (edit) {
        formdata.id = entity.id;
        update(formdata).then((err)=> {
          if (err) {
            message.error('更新数据失败。');
          } else {
            message.success('更新数据成功！');
            this.refs.pavf.resetFields();
            this.fetchModalData(productAttributeMappingId);
          }
        });
      } else {
        create(formdata).then((err)=> {
          if (err) {
            message.error('创建数据失败。');
          } else {
            message.success('创建数据成功！');
            this.refs.pavf.resetFields();
            this.fetchModalData(productAttributeMappingId);
          }
        });
      }
      this.onValueEditModalClose();
    });
  },

  onValueEditModalClose(){
    this.setState({showValueEditModal: false}, ()=> {
      this.refs.pavf.resetFields();
    });
  },

  render() {
    const { selectlist }= this.props.productAttribute;
    const columns = [{
      title: 'Id',
      dataIndex: 'id',
      sorter: true,
      width: '20%'
    }, {
      title: '属性名',
      dataIndex: 'productAttributeId',
      render: (productAttributeId)=> selectlist.find(x=>x.id == productAttributeId).name
    }, {
      title: '属性值',
      dataIndex: 'valueCount',
      render: (valueCount, record)=> {
        const attributeName = selectlist.find(x=>x.id == record.productAttributeId).name;
        return (
          <a onClick={this.onShowValueModal.bind(this,record.id, attributeName)}>查看/编辑 ({valueCount})</a>
        )
      }
    }, {
      title: '操作',
      key: 'operation',
      render: (text, record) => (
        <span>
          <Button type="ghost" shape="circle" icon="edit" size="small" title='编辑'
                  onClick={this.onEdit.bind(null,record)}/>
          <span className="ant-divider"></span>
          <Button type="ghost" shape="circle" icon="delete" size="small" title='删除'
                  onClick={this.onRemove.bind(null,record)}/>
        </span>
      )
    }];

    const valueEditColumns = [{
      title: 'Id',
      dataIndex: 'id',
      sorter: true,
      width: '20%'
    }, {
      title: '名称',
      dataIndex: 'name'
    }, {
      title: '价格调整',
      dataIndex: 'priceAdjustment'
    }, {
      title: '图片',
      dataIndex: 'imageUrl',
      render: (url) => <img src={url} style={{ width:'30px' ,height:'30px'}}/>
    }, {
      title: '操作',
      key: 'operation',
      render: (text, record) => (
        <span>
          <Button type="ghost" shape="circle" icon="edit" size="small" title='编辑'
                  onClick={this.onEditValue.bind(null,record)}/>
          <span className="ant-divider"></span>
          <Button type="ghost" shape="circle" icon="delete" size="small" title='删除'
                  onClick={this.onRemoveValue.bind(null,record)}/>
        </span>
      )
    }];
    const valueList = this.props.productAttributeValue.list;
    const valueEntity = this.props.productAttributeValue.entity;
    const valueLoading = this.props.productAttributeValue.loading;
    const { productAttributeMapping:{ loading, list, entity }} = this.props;
    const product = this.props.product.entity;
    const { title, visible, edit, showValueModal, showValueEditModal,valueTitle }=this.state;

    const data = list ? list.data : [];
    const pagination = Object.assign({}, this.state.pagination, {total: list ? list.recordCount : 0});
    const valuePagination = Object.assign({}, this.state.valuePagination, {total: valueList ? valueList.recordCount : 0});
    const valueData = valueList ? valueList.data : [];
    const { getFieldDecorator } = this.props.form;
    const record = edit ? entity : {};
    const formItemLayout = {
      labelCol: {span: 4},
      wrapperCol: {span: 20}
    };

    const checkAttribute = (rule, value, callback)=> {
      if (data.filter(item=>item.productAttributeId == value).length > 0) {
        callback(new Error('当前属性已经添加!'));
      } else {
        callback();
      }
    };

    return (
      <div className='container'>
        <div className='ant-list-header' data-flex="main:justify">
          <div>
            <Link to='product'>
              <Icon type='arrow-left'/> 返回列表
            </Link>
          </div>
          <div className='ant-list-header-right'>
            <Button type="primary" icon="plus" onClick={this.onAdd}>添加产品属性</Button>
          </div>
        </div>
        <div className='nav-tabs-container'>
          <ul className="nav nav-tabs">
            <li ><Link to={`product/update/${product.id}`}>基本信息</Link></li>
            <li><Link to={`productstoragequantity/${product.id}`}>管理库存</Link></li>
            <li><Link to={`productcarcate/${product.id}`}>车型匹配</Link></li>
            <li className="active"><a>产品属性</a></li>
            <li><Link to={`productspecificationattribute/${product.id}`}>产品规格</Link></li>
          </ul>
        </div>
        <Table
          ref='table'
          columns={columns}
          rowKey={record => record.id}
          dataSource={data}
          pagination={pagination}
          loading={loading}
          onChange={this.handleTableChange}
          />
        <Modal title={title} visible={visible} onOk={this.onModalSubmit}
               onCancel={this.onModalClose}>
          <Form horizontal>
            <FormItem
              {...formItemLayout}
              label="产品属性"
              >
              {getFieldDecorator('productAttributeId', {
                  initialValue: record.productAttributeId ? `${record.productAttributeId}` : '',
                  rules: [{required: true, message: '请选择产品属性'}, {validator: checkAttribute}]
                }
              )(
                <Select placeholder='请选择产品属性'>
                  {selectlist.map(item=> {
                    return (
                      <Option key={item.id}>{item.name}</Option>
                    )
                  })}
                </Select>
              )}
            </FormItem>
          </Form>
        </Modal>

        <Modal title={valueTitle} visible={showValueModal} width={'80%'} footer={<div style={{border:'none'}}/>}
               onCancel={this.onValueModalClose}>
          <div className='ant-list-header' data-flex="dir:right">
            <div className='ant-list-header-right'>
              <Button type="primary" icon="plus" onClick={this.onAddValue}>添加属性值</Button>
            </div>
          </div>
          <Table
            ref='valueTable'
            columns={valueEditColumns}
            rowKey={record => record.id}
            dataSource={valueData}
            pagination={valuePagination}
            loading={valueLoading}
            onChange={this.handleValueTableChange}
            />
        </Modal>

        <Modal title={title} visible={showValueEditModal}
               onOk={this.onValueSubmit}
               onCancel={this.onValueEditModalClose}>
          <ProductAttributeValueForm ref='pavf' entity={edit?valueEntity:{}} product={product}/>
        </Modal>
      </div>
    );
  }
});

function mapStateToProps(state) {
  return {
    auth: state.auth,
    productAttributeMapping: state.productAttributeMapping,
    productAttribute: state.productAttribute,
    productAttributeValue: state.productAttributeValue,
    product: state.product
  }
}

function mapDispatchToProps(dispatch) {
  return {
    authActions: bindActionCreators(authActions, dispatch),
    productActions: bindActionCreators(productActions, dispatch),
    productAttributeActions: bindActionCreators(productAttributeActions, dispatch),
    productAttributeValueActions: bindActionCreators(productAttributeValueActions, dispatch),
    productAttributeMappingActions: bindActionCreators(productAttributeMappingActions, dispatch)

  }
}

const statics = {
  path: 'productattributemapping',
  menuGroup: 'product',
  breadcrumb: [{
    title: '产品中心'
  }, {
    title: '关联产品属性'
  }]
};

ProductAttributeMapping = createForm()(ProductAttributeMapping);

export default connectStatic(statics)(connect(mapStateToProps, mapDispatchToProps)(ProductAttributeMapping))
