// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class ProductAttributeCategoryMappingService : IProductAttributeCategoryMappingService
    {
		   #region Fields

        private readonly IRepository<ProductAttributeCategoryMapping> _ProductAttributeCategoryMappingRepository;

        #endregion

        #region Ctor

        public ProductAttributeCategoryMappingService(IRepository<ProductAttributeCategoryMapping> ProductAttributeCategoryMappingRepository
           )
        {
            this._ProductAttributeCategoryMappingRepository = ProductAttributeCategoryMappingRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(ProductAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeCategoryMapping");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<ProductAttributeCategoryMapping> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _ProductAttributeCategoryMappingRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<ProductAttributeCategoryMapping> GetAll()
        {
            return _ProductAttributeCategoryMappingRepository.Table;
        }

        public IPagedList<ProductAttributeCategoryMapping> GetPageList(int pageIndex, int pageSize)
        {
            var query = _ProductAttributeCategoryMappingRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<ProductAttributeCategoryMapping>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(ProductAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeCategoryMapping");
            return await _ProductAttributeCategoryMappingRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(ProductAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ProductAttributeCategoryMapping");

            return await _ProductAttributeCategoryMappingRepository.UpdateAsync(entity);
        }
    }
}
