// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using SQ.Core.Data;
using MB.Data.Service;
using MB.Data.Models;
using System.Threading.Tasks;

namespace MB.Data.Impl
{
	public class SpecificationAttributeCategoryMappingService : ISpecificationAttributeCategoryMappingService
    {
		   #region Fields

        private readonly IRepository<SpecificationAttributeCategoryMapping> _SpecificationAttributeCategoryMappingRepository;

        #endregion

        #region Ctor

        public SpecificationAttributeCategoryMappingService(IRepository<SpecificationAttributeCategoryMapping> SpecificationAttributeCategoryMappingRepository
           )
        {
            this._SpecificationAttributeCategoryMappingRepository = SpecificationAttributeCategoryMappingRepository;

        }
        #endregion

        public async Task<int> DeleteAsync(SpecificationAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("SpecificationAttributeCategoryMapping");

            entity.Deleted = true;
           return await UpdateAsync(entity);
        }

        public async Task<SpecificationAttributeCategoryMapping> FindOneAsync(int Id)
        {
            if (Id == 0)
                return null;

            var entity = await _SpecificationAttributeCategoryMappingRepository.GetByIdAsync(Id);
            return entity;
        }

        public IQueryable<SpecificationAttributeCategoryMapping> GetAll()
        {
            return _SpecificationAttributeCategoryMappingRepository.Table;
        }

        public IPagedList<SpecificationAttributeCategoryMapping> GetPageList(int pageIndex, int pageSize)
        {
            var query = _SpecificationAttributeCategoryMappingRepository.Table;
            query = query.OrderByDescending(a => a.Id);
            var result = new PagedList<SpecificationAttributeCategoryMapping>(query, pageIndex, pageSize);
            return result;
        }

        public async Task<int> InsertAsync(SpecificationAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("SpecificationAttributeCategoryMapping");
            return await _SpecificationAttributeCategoryMappingRepository.InsertAsync(entity);
        }

        public async Task<int> UpdateAsync(SpecificationAttributeCategoryMapping entity)
        {
            if (entity == null)
                throw new ArgumentNullException("SpecificationAttributeCategoryMapping");

            return await _SpecificationAttributeCategoryMappingRepository.UpdateAsync(entity);
        }
    }
}
