// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as departmentTypes from '../contants/department';

const initialState = {
};

export default function department(state = initialState, action = {}) {
	switch (action.type) {
		case authTypes.GET_ALL_DEPARTMENT:
		case authTypes.GET_ONE_DEPARTMENT:
		case authTypes.CREATE_DEPARTMENT:
		case authTypes.UPDATE_DEPARTMENT:
		case authTypes.DELETE_DEPARTMENT:
			return {
				...state,
				loading: true
			};
		case authTypes.GET_ALL_DEPARTMENT_FAIL:
		case authTypes.GET_ONE_DEPARTMENT_FAIL:
		case authTypes.CREATE_DEPARTMENT_FAIL:
		case authTypes.UPDATE_DEPARTMENT_FAIL:
		case authTypes.DELETE_DEPARTMENT_FAIL:
			return {
				...state,
				loading: false,
				error: action.error
			};
		case authTypes.GET_ALL_DEPARTMENT_SUCCESS:
			return {
				...state,
				loading: false,
				list: action.result
			};
		case authTypes.GET_ONE_DEPARTMENT_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.CREATE_DEPARTMENT_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.UPDATE_DEPARTMENT_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.DELETE_DEPARTMENT_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		default:
			return state;
  }
}

