// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


import * as jobTypes from '../contants/job';

const initialState = {
};

export default function job(state = initialState, action = {}) {
	switch (action.type) {
		case authTypes.GET_ALL_JOB:
		case authTypes.GET_ONE_JOB:
		case authTypes.CREATE_JOB:
		case authTypes.UPDATE_JOB:
		case authTypes.DELETE_JOB:
			return {
				...state,
				loading: true
			};
		case authTypes.GET_ALL_JOB_FAIL:
		case authTypes.GET_ONE_JOB_FAIL:
		case authTypes.CREATE_JOB_FAIL:
		case authTypes.UPDATE_JOB_FAIL:
		case authTypes.DELETE_JOB_FAIL:
			return {
				...state,
				loading: false,
				error: action.error
			};
		case authTypes.GET_ALL_JOB_SUCCESS:
			return {
				...state,
				loading: false,
				list: action.result
			};
		case authTypes.GET_ONE_JOB_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.CREATE_JOB_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.UPDATE_JOB_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		case authTypes.DELETE_JOB_SUCCESS:
			return {
				...state,
				loading: false,
				entity: action.result
			};
		default:
			return state;
  }
}

