// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as manufacturerTypes from '../contants/manufacturer';

const initialState = {
  loaded: false,
  entity: {},
  selectlist:[]
};

export default function manufacturer(state = initialState, action = {}) {
  switch (action.type) {
    case manufacturerTypes.GET_ALL_MANUFACTURER:
    case manufacturerTypes.GET_ONE_MANUFACTURER:
    case manufacturerTypes.CREATE_MANUFACTURER:
    case manufacturerTypes.UPDATE_MANUFACTURER:
    case manufacturerTypes.DELETE_MANUFACTURER:
    case manufacturerTypes.GET_MANUFACTURER_SELECTLIST:
      return {
        ...state,
        loading: true
      };
    case manufacturerTypes.GET_ALL_MANUFACTURER_FAIL:
    case manufacturerTypes.GET_ONE_MANUFACTURER_FAIL:
    case manufacturerTypes.CREATE_MANUFACTURER_FAIL:
    case manufacturerTypes.UPDATE_MANUFACTURER_FAIL:
    case manufacturerTypes.DELETE_MANUFACTURER_FAIL:
    case manufacturerTypes.GET_MANUFACTURER_SELECTLIST_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case manufacturerTypes.GET_MANUFACTURER_SELECTLIST_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        selectlist: action.result
      };
    case manufacturerTypes.GET_ALL_MANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case manufacturerTypes.GET_ONE_MANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case manufacturerTypes.CREATE_MANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case manufacturerTypes.UPDATE_MANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case manufacturerTypes.DELETE_MANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

