// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productTypes from '../contants/product';

const initialState = {
  loaded: false,
  entity: {}
};

export default function product(state = initialState, action = {}) {
  switch (action.type) {
    case productTypes.GET_ALL_PRODUCT:
    case productTypes.GET_ONE_PRODUCT:
    case productTypes.CREATE_PRODUCT:
    case productTypes.UPDATE_PRODUCT:
    case productTypes.DELETE_PRODUCT:
      return {
        ...state,
        loading: true
      };
    case productTypes.GET_ALL_PRODUCT_FAIL:
    case productTypes.GET_ONE_PRODUCT_FAIL:
    case productTypes.CREATE_PRODUCT_FAIL:
    case productTypes.UPDATE_PRODUCT_FAIL:
    case productTypes.DELETE_PRODUCT_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productTypes.GET_ALL_PRODUCT_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productTypes.GET_ONE_PRODUCT_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productTypes.CREATE_PRODUCT_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productTypes.UPDATE_PRODUCT_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productTypes.DELETE_PRODUCT_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

