// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productManufacturerTypes from '../contants/productManufacturer';

const initialState = {
  loaded: false,
  entity: {}
};

export default function productManufacturer(state = initialState, action = {}) {
  switch (action.type) {
    case productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER:
    case productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER:
    case productManufacturerTypes.CREATE_PRODUCTMANUFACTURER:
    case productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER:
    case productManufacturerTypes.DELETE_PRODUCTMANUFACTURER:
      return {
        ...state,
        loading: true
      };
    case productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER_FAIL:
    case productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER_FAIL:
    case productManufacturerTypes.CREATE_PRODUCTMANUFACTURER_FAIL:
    case productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER_FAIL:
    case productManufacturerTypes.DELETE_PRODUCTMANUFACTURER_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productManufacturerTypes.GET_ALL_PRODUCTMANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productManufacturerTypes.GET_ONE_PRODUCTMANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productManufacturerTypes.CREATE_PRODUCTMANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productManufacturerTypes.UPDATE_PRODUCTMANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productManufacturerTypes.DELETE_PRODUCTMANUFACTURER_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

