// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productSpecificationAttributeTypes from '../contants/productSpecificationAttribute';

const initialState = {
  loaded: false,
  entity: {}
};

export default function productSpecificationAttribute(state = initialState, action = {}) {
  switch (action.type) {
    case productSpecificationAttributeTypes.GET_ALL_PRODUCTSPECIFICATIONATTRIBUTE:
    case productSpecificationAttributeTypes.GET_ONE_PRODUCTSPECIFICATIONATTRIBUTE:
    case productSpecificationAttributeTypes.CREATE_PRODUCTSPECIFICATIONATTRIBUTE:
    case productSpecificationAttributeTypes.UPDATE_PRODUCTSPECIFICATIONATTRIBUTE:
    case productSpecificationAttributeTypes.DELETE_PRODUCTSPECIFICATIONATTRIBUTE:
      return {
        ...state,
        loading: true
      };
    case productSpecificationAttributeTypes.GET_ALL_PRODUCTSPECIFICATIONATTRIBUTE_FAIL:
    case productSpecificationAttributeTypes.GET_ONE_PRODUCTSPECIFICATIONATTRIBUTE_FAIL:
    case productSpecificationAttributeTypes.CREATE_PRODUCTSPECIFICATIONATTRIBUTE_FAIL:
    case productSpecificationAttributeTypes.UPDATE_PRODUCTSPECIFICATIONATTRIBUTE_FAIL:
    case productSpecificationAttributeTypes.DELETE_PRODUCTSPECIFICATIONATTRIBUTE_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productSpecificationAttributeTypes.GET_ALL_PRODUCTSPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productSpecificationAttributeTypes.GET_ONE_PRODUCTSPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productSpecificationAttributeTypes.CREATE_PRODUCTSPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productSpecificationAttributeTypes.UPDATE_PRODUCTSPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productSpecificationAttributeTypes.DELETE_PRODUCTSPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

