// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productCarCateTypes from '../contants/productCarCate';

const initialState = {
  loaded: false,
  entity: {}
};

export default function productCarCate(state = initialState, action = {}) {
  switch (action.type) {
    case productCarCateTypes.GET_ALL_PRODUCTCARCATE:
    case productCarCateTypes.GET_ONE_PRODUCTCARCATE:
    case productCarCateTypes.CREATE_PRODUCTCARCATE:
    case productCarCateTypes.UPDATE_PRODUCTCARCATE:
    case productCarCateTypes.DELETE_PRODUCTCARCATE:
      return {
        ...state,
        loading: true
      };
    case productCarCateTypes.GET_ALL_PRODUCTCARCATE_FAIL:
    case productCarCateTypes.GET_ONE_PRODUCTCARCATE_FAIL:
    case productCarCateTypes.CREATE_PRODUCTCARCATE_FAIL:
    case productCarCateTypes.UPDATE_PRODUCTCARCATE_FAIL:
    case productCarCateTypes.DELETE_PRODUCTCARCATE_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productCarCateTypes.GET_ALL_PRODUCTCARCATE_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productCarCateTypes.GET_ONE_PRODUCTCARCATE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productCarCateTypes.CREATE_PRODUCTCARCATE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productCarCateTypes.UPDATE_PRODUCTCARCATE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productCarCateTypes.DELETE_PRODUCTCARCATE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

