// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as productAttributeMappingTypes from '../contants/productAttributeMapping';

const initialState = {
  loaded: false,
  entity: {}
};

export default function productAttributeMapping(state = initialState, action = {}) {
  switch (action.type) {
    case productAttributeMappingTypes.GET_ALL_PRODUCTATTRIBUTEMAPPING:
    case productAttributeMappingTypes.GET_ONE_PRODUCTATTRIBUTEMAPPING:
    case productAttributeMappingTypes.CREATE_PRODUCTATTRIBUTEMAPPING:
    case productAttributeMappingTypes.UPDATE_PRODUCTATTRIBUTEMAPPING:
    case productAttributeMappingTypes.DELETE_PRODUCTATTRIBUTEMAPPING:
      return {
        ...state,
        loading: true
      };
    case productAttributeMappingTypes.GET_ALL_PRODUCTATTRIBUTEMAPPING_FAIL:
    case productAttributeMappingTypes.GET_ONE_PRODUCTATTRIBUTEMAPPING_FAIL:
    case productAttributeMappingTypes.CREATE_PRODUCTATTRIBUTEMAPPING_FAIL:
    case productAttributeMappingTypes.UPDATE_PRODUCTATTRIBUTEMAPPING_FAIL:
    case productAttributeMappingTypes.DELETE_PRODUCTATTRIBUTEMAPPING_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case productAttributeMappingTypes.GET_ALL_PRODUCTATTRIBUTEMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case productAttributeMappingTypes.GET_ONE_PRODUCTATTRIBUTEMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeMappingTypes.CREATE_PRODUCTATTRIBUTEMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeMappingTypes.UPDATE_PRODUCTATTRIBUTEMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case productAttributeMappingTypes.DELETE_PRODUCTATTRIBUTEMAPPING_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

