// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>



import * as specificationAttributeTypes from '../contants/specificationAttribute';

const initialState = {
  loaded: false,
  entity: {}
};

export default function specificationAttribute(state = initialState, action = {}) {
  switch (action.type) {
    case specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE:
    case specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE:
    case specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE:
    case specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE:
    case specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE:
      return {
        ...state,
        loading: true
      };
    case specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE_FAIL:
    case specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE_FAIL:
    case specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE_FAIL:
    case specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE_FAIL:
    case specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE_FAIL:
      return {
        ...state,
        loading: false,
        error: action.error
      };
    case specificationAttributeTypes.GET_ALL_SPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        loaded: true,
        list: action.result
      };
    case specificationAttributeTypes.GET_ONE_SPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case specificationAttributeTypes.CREATE_SPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case specificationAttributeTypes.UPDATE_SPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    case specificationAttributeTypes.DELETE_SPECIFICATIONATTRIBUTE_SUCCESS:
      return {
        ...state,
        loading: false,
        entity: action.result
      };
    default:
      return state;
  }
}

