// <autogenerated>
//   This file was generated by T4 code generator Entry.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


export const GET_ALL_BANNER = 'GET_ALL_BANNER';
export const GET_ALL_BANNER_SUCCESS = 'GET_ALL_BANNER_SUCCESS';
export const GET_ALL_BANNER_FAIL = 'GET_ALL_BANNER_FAIL';

export const GET_ONE_BANNER = 'GET_ONE_BANNER';
export const GET_ONE_BANNER_SUCCESS = 'GET_ONE_BANNER_SUCCESS';
export const GET_ONE_BANNER_FAIL = 'GET_ONE_BANNER_FAIL';

export const CREATE_BANNER = 'CREATE_BANNER';
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS';
export const CREATE_BANNER_FAIL = 'CREATE_BANNER_FAIL';

export const UPDATE_BANNER = 'UPDATE_BANNER';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL';

export const DELETE_BANNER = 'DELETE_BANNER';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_FAIL = 'DELETE_BANNER_FAIL';

